In [8]:
# Load the Pandas libraries with alias 'pd' 

import pandas as pd

In [10]:
# Read data from file 'International Arrivals.csv' that contains for each country or zone the number of international arrivals per year

arrivals=pd.read_csv('International Arrivals.csv', header=2)

#Select only the columns needed. Exclude information from 1960 to 1994 and 2018 that is empty

arrivals=arrivals[['Country Name', 'Country Code', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017']]

In [11]:
#Check the arrivals data frame

arrivals

,Country Name,Country Code,1995,1996,1997,1998,1999,2000,2001,2002,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Aruba,ABW,6.190000e+05,6.410000e+05,6.500000e+05,6.470000e+05,6.830000e+05,7.210000e+05,6.910000e+05,6.430000e+05,...,8.270000e+05,8.130000e+05,8.240000e+05,8.690000e+05,9.040000e+05,9.790000e+05,1.072000e+06,1.225000e+06,1.102000e+06,1.070500e+06
1,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Angola,AGO,9.000000e+03,2.100000e+04,4.500000e+04,5.200000e+04,4.500000e+04,5.100000e+04,6.700000e+04,9.100000e+04,...,2.940000e+05,3.660000e+05,4.250000e+05,4.810000e+05,5.280000e+05,6.500000e+05,5.950000e+05,5.920000e+05,3.970000e+05,2.610000e+05
3,Albania,ALB,3.040000e+05,2.870000e+05,1.190000e+05,1.840000e+05,3.710000e+05,3.170000e+05,3.540000e+05,4.700000e+05,...,1.247000e+06,1.711000e+06,2.191000e+06,2.469000e+06,3.156000e+06,2.857000e+06,3.341000e+06,3.784000e+06,4.070000e+06,4.643000e+06
4,Andorra,AND,NaN,NaN,NaN,NaN,2.347000e+06,2.949000e+06,3.516000e+06,3.387000e+06,...,2.059000e+06,1.830000e+06,1.808000e+06,2.242000e+06,2.238000e+06,2.328000e+06,2.363000e+06,2.663000e+06,2.831000e+06,NaN
5,Arab World,ARB,2.115522e+07,2.192905e+07,2.384332e+07,2.623208e+07,3.010843e+07,3.391257e+07,3.478617e+07,3.904145e+07,...,7.456862e+07,7.372749e+07,8.459515e+07,7.090156e+07,7.899196e+07,7.869716e+07,8.415708e+07,7.885381e+07,7.636341e+07,8.221460e+07
6,United Arab Emirates,ARE,2.315000e+06,2.572000e+06,2.476000e+06,2.991000e+06,3.393000e+06,3.907000e+06,4.134000e+06,5.445000e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Argentina,ARG,2.289000e+06,2.614000e+06,2.764000e+06,3.012000e+06,2.898000e+06,2.909000e+06,2.620000e+06,2.820000e+06,...,4.700000e+06,4.308000e+06,5.325000e+06,5.705000e+06,5.587000e+06,5.246000e+06,5.931000e+06,5.736000e+06,6.655000e+06,6.720000e+06
8,Armenia,ARM,1.200000e+04,1.300000e+04,2.300000e+04,3.200000e+04,4.100000e+04,4.500000e+04,1.230000e+05,1.620000e+05,...,5.580000e+05,5.750000e+05,6.840000e+05,7.580000e+05,9.630000e+05,1.084000e+06,1.204000e+06,1.192000e+06,1.260000e+06,1.495000e+06
9,American Samoa,ASM,3.400000e+04,3.500000e+04,2.600000e+04,3.600000e+04,4.100000e+04,4.400000e+04,3.600000e+04,NaN,...,2.430000e+04,2.350000e+04,2.310000e+04,2.260000e+04,2.260000e+04,2.080000e+04,2.160000e+04,2.030000e+04,2.010000e+04,2.000000e+04
10,Antigua and Barbuda,ATG,2.200000e+05,2.280000e+05,2.400000e+05,2.340000e+05,2.320000e+05,2.070000e+05,2.150000e+05,2.180000e+05,...,2.660000e+05,2.340000e+05,2.300000e+05,2.410000e+05,2.470000e+05,2.430000e+05,2.490000e+05,2.500000e+05,2.650000e+05,2.470000e+05
11,Australia,AUS,3.726000e+06,4.165000e+06,4.318000e+06,4.167000e+06,4.459000e+06,4.931000e+06,4.856000e+06,4.841000e+06,...,5.586000e+06,5.490000e+06,5.790000e+06,5.771000e+06,6.032000e+06,6.482000e+06,6.922000e+06,7.450000e+06,8.269000e+06,8.815000e+06
12,Austria,AUT,1.717300e+07,1.709000e+07,1.664700e+07,1.735200e+07,1.746700e+07,1.798200e+07,1.818000e+07,1.861100e+07,...,2.193500e+07,2.135500e+07,2.200400e+07,2.301200e+07,2.415100e+07,2.481300e+07,2.529100e+07,2.672800e+07,2.812100e+07,2.946000e+07
13,Azerbaijan,AZE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.760000e+05,...,1.043000e+06,1.005000e+06,1.280000e+06,1.562000e+06,1.986000e+06,2.130000e+06,2.160000e+06,1.922000e+06,2.044000e+06,2.454000e+06
14,Burundi,BDI,3.400000e+04,2.700000e+04,1.100000e+04,1.500000e+04,2.600000e+04,2.900000e+04,3.600000e+04,7.400000e+04,...,2.020000e+05,2.120000e+05,1.420000e+05,1.440000e+05,1.470000e+05,2.340000e+05,2.350000e+05,1.310000e+05,1.870000e+05,2.990000e+05
15,Belgium,BEL,5.560000e+06,5.829000e+06,6.037000e+06,6.179000e+06,6.369000e+06,6.457000e+06,6.452000e+06,6.720000e+06,...,7.165000e+06,6.815000e+06,7.186000e+06,7.494000e+06,7.560000e+06,7.684000e+06,7.887000e+06,8.355000e+06,7.481000e+06,8.385000e+06
16,Benin,BEN,1.380000e+05,1.430000e+05,1.480000e+05,1.520000e+05,8.000000e+04,9.600000e+04,8.800000e+04,7.200000e+04,...,1.880000e+05,1.900000e+05,1.990000e+05,2.090000e+05,2.200000e+05,2.310000e+05,2.420000e+05,2.550000e+05,2.670000e+05,2.810000e+05
17,Burkina Faso,BFA,1.240000e+05,1.310000e+05,1.380000e+05,1.600000e+05,1.170000e+05,1.260000e+05,1.280000e+05,1.500000e+05,...,2.720000e+05,2.690000e+05,2.740000e+05,2.380000e+05,2.370000e+05,2.180000e+05,1.910000e+05,1.630000e+05,1.520000e+05,1.430000e+05
18,Bangladesh,BGD,1.560000e+05,1.660000e+05,1.820000e+05,1.720000e+05,1.730000e+05,1.990000e+05,2.070000e+05,2.070000e+05,...,4.670000e+05,2.670000e+05,3.030000e+05,1.550000e+05,1.250000e+05,1.480000e+05,1.250000e+05,NaN,NaN,NaN
19,Bulgaria,BGR,3.466000e+06,2.795000e+06,2.980000e+06,2.667000e+06,2.472000e+06,2.785000e+06,3.186000e+06,3.433000e+06,...,5.780000e+06,5.739000e+06,6.047000e+06,6.328000e+06,6.541000e+06,6.898000e+06,7.311000e+06,7.099000e+06,8.252000e+06,8.883000e+06
20,Bahrain,BHR,2.311000e+06,1.988000e+06,2.600000e+06,2.898000e+06,3.280000e+06,3.869000e+06,4.388000e+06,4.831000e+06,...,8.631000e+06,8.861000e+06,1.195200e+07,6.732000e+06,8.062000e+06,9.163000e+06,1.045200e+07,9.670000e+06,1.015800e+07,1.137000e+07
21,"Bahamas, The",BHS,1.598000e+06,1.633000e+06,1.618000e+06,1.528000e+06,1.577000e+06,1.544000e+06,1.538000e+06,1.513000e+06,...,1.463000e+06,1.327000e+06,1.370000e+06,1.346000e+06,1.422000e+06,1.366000e+06,1.427000e+06,1.484000e+06,1.499000e+06,1.439000e+06
22,Bosnia and Herzegovina,BIH,NaN,NaN,1.150000e+05,1.480000e+05,1.470000e+05,1.710000e+05,1.390000e+05,1.600000e+05,...,3.220000e+05,3.110000e+05,3.650000e+05,3.920000e+05,4.390000e+05,5.290000e+05,5.360000e+05,6.780000e+05,7.780000e+05,9.230000e+05
23,Belarus,BLR,1.606000e+05,2.340000e+05,2.535000e+05,3.550000e+05,7.490000e+04,6.000000e+04,6.100000e+04,6.300000e+04,...,9.050000e+04,9.500000e+04,1.193000e+05,1.160000e+05,6.129900e+06,6.241800e+06,5.374900e+06,4.385600e+06,1.093540e+07,1.106020e+07
24,Belize,BLZ,1.310000e+05,1.330000e+05,1.460000e+05,1.760000e+05,1.810000e+05,1.960000e+05,1.960000e+05,2.000000e+05,...,2.450000e+05,2.320000e+05,2.420000e+05,2.500000e+05,2.770000e+05,2.940000e+05,3.210000e+05,3.410000e+05,3.860000e+05,4.270000e+05
25,Bermuda,BMU,3.870000e+05,3.900000e+05,3.800000e+05,3.700000e+05,3.550000e+05,3.320000e+05,2.780000e+05,2.840000e+05,...,2.640000e+05,2.360000e+05,2.320000e+05,2.360000e+05,2.320000e+05,2.360000e+05,2.240000e+05,2.200000e+05,2.440000e+05,2.700000e+05
26,Bolivia,BOL,2.840000e+05,3.130000e+05,3.550000e+05,3.870000e+05,3.420000e+05,3.190000e+05,3.160000e+05,3.340000e+05,...,5.940000e+05,5.990000e+05,6.790000e+05,7.110000e+05,7.980000e+05,7.980000e+05,8.710000e+05,8.820000e+05,9.590000e+05,1.134000e+06
27,Brazil,BRA,1.991000e+06,2.666000e+06,2.850000e+06,4.818000e+06,5.107000e+06,5.313000e+06,4.773000e+06,3.785000e+06,...,5.050000e+06,4.802000e+06,5.161000e+06,5.433000e+06,5.677000e+06,5.813000e+06,6.430000e+06,6.306000e+06,6.547000e+06,6.589000e+06
28,Barbados,BRB,4.420000e+05,4.470000e+05,4.720000e+05,5.120000e+05,5.150000e+05,5.450000e+05,5.070000e+05,4.980000e+05,...,5.680000e+05,5.190000e+05,5.320000e+05,5.680000e+05,5.360000e+05,5.090000e+05,5.210000e+05,5.920000e+05,6.320000e+05,6.640000e+05
29,Brunei Darussalam,BRN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.260000e+05,1.570000e+05,2.140000e+05,2.420000e+05,2.090000e+05,2.250000e+05,2.010000e+05,2.180000e+05,2.190000e+05,2.590000e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Latin America & the Caribbean (IDA & IBRD coun...,TLA,3.866900e+07,4.055500e+07,4.014200e+07,4.289600e+07,4.307600e+07,4.580400e+07,4.420500e+07,4.240700e+07,...,6.054600e+07,5.873000e+07,6.136500e+07,6.495000e+07,6.732700e+07,6.889840e+07,7.719810e+07,8.303000e+07,8.976419e+07,9.818026e+07
235,Timor-Leste,TLS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.600000e+04,4.400000e+04,4.000000e+04,5.100000e+04,5.800000e+04,7.900000e+04,6.000000e+04,6.200000e+04,6.600000e+04,7.400000e+04
236,Middle East & North Africa (IDA & IBRD countries),TMN,1.362004e+07,1.439085e+07,1.570795e+07,1.722888e+07,1.983101e+07,2.198938e+07,2.209232e+07,2.406148e+07,...,4.431138e+07,4.705281e+07,5.473675e+07,4.426041e+07,4.803150e+07,4.760095e+07,4.810056e+07,4.403788e+07,4.003877e+07,4.723084e+07
237,Tonga,TON,2.900000e+04,2.700000e+04,2.600000e+04,2.700000e+04,3.100000e+04,3.500000e+04,3.200000e+04,3.700000e+04,...,5.000000e+04,4.570000e+04,4.710000e+04,4.600000e+04,4.740000e+04,4.820000e+04,5.040000e+04,5.380000e+04,5.910000e+04,6.250000e+04
238,South Asia (IDA & IBRD),TSA,3.809177e+06,3.930662e+06,4.161829e+06,4.280669e+06,4.529947e+06,4.826436e+06,4.486400e+06,4.321774e+06,...,8.365578e+06,8.065426e+06,9.234491e+06,1.039236e+07,1.072507e+07,1.168277e+07,1.891533e+07,1.919519e+07,2.129414e+07,2.284510e+07
239,Sub-Saharan Africa (IDA & IBRD countries),TSS,1.295720e+07,1.474029e+07,1.469061e+07,1.665619e+07,1.731444e+07,1.757944e+07,1.812036e+07,1.941256e+07,...,3.060059e+07,2.833533e+07,3.145731e+07,3.310224e+07,3.426820e+07,3.546457e+07,3.677882e+07,3.718509e+07,4.069832e+07,4.236450e+07
240,Trinidad and Tobago,TTO,2.600000e+05,2.660000e+05,3.240000e+05,3.340000e+05,3.580000e+05,3.990000e+05,3.830000e+05,3.840000e+05,...,4.370000e+05,4.190000e+05,3.880000e+05,4.310000e+05,4.550000e+05,4.340000e+05,4.120000e+05,4.400000e+05,4.090000e+05,3.950000e+05
241,Tunisia,TUN,4.120000e+06,3.885000e+06,4.263000e+06,4.718000e+06,4.832000e+06,5.058000e+06,5.387000e+06,5.064000e+06,...,7.050000e+06,7.797000e+06,7.828000e+06,5.746000e+06,6.999000e+06,7.352000e+06,7.163000e+06,5.359000e+06,5.724000e+06,7.052000e+06
242,Turkey,TUR,7.083000e+06,7.966000e+06,9.040000e+06,8.960000e+06,6.893000e+06,9.586000e+06,1.078300e+07,1.279000e+07,...,2.979200e+07,3.018700e+07,3.136400e+07,3.465400e+07,3.569800e+07,3.779500e+07,3.981100e+07,3.947800e+07,3.028900e+07,3.760100e+07
243,Tuvalu,TUV,9.000000e+02,1.000000e+03,1.000000e+03,1.000000e+03,1.100000e+03,1.100000e+03,1.100000e+03,1.300000e+03,...,1.700000e+03,1.600000e+03,1.700000e+03,1.200000e+03,1.100000e+03,1.300000e+03,1.400000e+03,2.400000e+03,2.500000e+03,2.500000e+03
244,Tanzania,TZA,2.850000e+05,3.150000e+05,3.470000e+05,4.500000e+05,5.640000e+05,4.590000e+05,5.010000e+05,5.500000e+05,...,7.500000e+05,6.950000e+05,7.540000e+05,8.430000e+05,1.043000e+06,1.063000e+06,1.113000e+06,1.104000e+06,1.233000e+06,1.275000e+06
245,Uganda,UGA,1.600000e+05,1.740000e+05,1.750000e+05,1.950000e+05,1.890000e+05,1.930000e+05,2.050000e+05,2.540000e+05,...,8.440000e+05,8.070000e+05,9.460000e+05,1.151000e+06,1.197000e+06,1.206000e+06,1.266000e+06,1.303000e+06,1.323000e+06,1.402000e+06
246,Ukraine,UKR,3.716000e+06,3.854000e+06,7.558000e+06,6.208000e+06,4.232000e+06,6.431000e+06,9.174000e+06,1.051700e+07,...,2.544900e+07,2.079800e+07,2.120300e+07,2.141500e+07,2.301300e+07,2.467100e+07,1.271200e+07,1.242800e+07,1.333300e+07,1.423000e+07
247,Upper middle income,UMC,1.065449e+08,1.181832e+08,1.206538e+08,1.251263e+08,1.323729e+08,1.495985e+08,1.561402e+08,1.672680e+08,...,2.472731e+08,2.397889e+08,2.576097e+08,2.759217e+08,2.971059e+08,3.098793e+08,3.227713e+08,3.332267e+08,3.382353e+08,3.635761e+08
248,Uruguay,URY,2.022000e+06,2.152000e+06,2.316000e+06,2.163000e+06,2.073000e+06,1.968000e+06,1.892000e+06,1.258000e+06,...,1.938000e+06,2.055000e+06,2.353000e+06,2.857000e+06,2.695000e+06,2.683000e+06,2.682000e+06,2.773000e+06,3.037000e+06,3.674000e+06
249,United States,USA,4.331800e+07,4.648900e+07,4.776700e+07,4.637700e+07,4.850900e+07,5.123800e+07,4.692700e+07,4.358100e+07,...,5.800700e+07,5.510300e+07,6.001000e+07,6.282100e+07,6.665700e+07,6.999500e+07,7.502200e+07,7.777400e+07,7.640700e+07,7.694100e+07
250,Uzbekistan,UZB,9.200000e+04,1.730000e+05,9.600000e+05,8.110000e+05,4.870000e+05,3.020000e+05,3.450000e+05,3.320000e+05,...,1.069000e+06,1.215000e+06,9.750000e+05,NaN,NaN,1.969000e+06,1.862000e+06,1.918000e+06,2.027000e+06,2.690000e+06
251,St. Vincent and the Grenadines,VCT,6.000000e+04,5.800000e+04,6.500000e+04,6.700000e+04,6.800000e+04,7.300000e+04,7.100000e+04,7.800000e+04,...,8.400000e+04,7.500000e+04,7.200000e+04,7.400000e+04,7.400000e+04,7.200000e+04,7.100000e+04,7.500000e+04,7.900000e+04,7.600000e+04
252,"Venezuela, RB",VEN,7.000000e+05,7.590000e+05,8.140000e+05,6.850000e+05,5.870000e+05,4.690000e+05,5.840000e+05,4.320000e+05,...,6.990000e+05,5.620000e+05,5.260000e+05,5.950000e+05,9.880000e+05,9.860000e+05,8.570000e+05,7.890000e+05,6.010000e+05,4.270000e+05
253,British Virgin Islands,VGB,2.190000e+05,2.440000e+05,2.440000e+05,2.790000e+05,2.840000e+05,2.720000e+05,2.960000e+05,2.820000e+05,...,3.460000e+05,3.090000e+05,3.300000e+05,3.380000e+05,3.510000e+05,3.660000e+05,3.860000e+05,3.930000e+05,4.080000e+05,3.350000e+05
254,Virgin Islands (U.S.),VIR,4.540000e+05,3.730000e+05,3.930000e+05,4.220000e+05,4.840000e+05,5.460000e+05,5.270000e+05,5.200000e+05,...,5.740000e+05,5.630000e+05,5.720000e+05,5.670000e+05,6.190000e+05,5.900000e+05,6.150000e+05,6.420000e+05,6.670000e+05,NaN
255,Vietnam,VNM,1.351000e+06,1.607000e+06,1.716000e+06,1.520000e+06,1.782000e+06,2.140000e+06,2.330000e+06,2.628000e+06,...,4.236000e+06,3.747000e+06,5.050000e+06,6.014000e+06,6.848000e+06,7.572000e+06,7.874000e+06,7.944000e+06,1.001300e+07,1.292200e+07
256,Vanuatu,VUT,4.400000e+04,4.600000e+04,5.000000e+04,5.200000e+04,5.100000e+04,5.800000e+04,5.300000e+04,4.900000e+04,...,9.050000e+04,1.007000e+05,9.720000e+04,9.400000e+04,1.082000e+05,1.100000e+05,1.090000e+05,9.000000e+04,9.510000e+04,1.090000e+05
257,World,WLD,5.239096e+08,5.545516e+08,5.843048e+08,6.022473e+08,6.272079e+08,6.773870e+08,6.782462e+08,6.984316e+08,...,9.363609e+08,8.975338e+08,9.563723e+08,9.975553e+08,1.054602e+09,1.106732e+09,1.159450e+09,1.206216e+09,1.250468e+09,1.341457e+09
258,Samoa,WSM,6.800000e+04,7.300000e+04,6.800000e+04,7.800000e+04,8.500000e+04,8.800000e+04,8.800000e+04,8.900000e+04,...,1.180000e+05,1.220000e+05,1.220000e+05,1.210000e+05,1.260000e+05,1.160000e+05,1.204000e+05,1.280000e+05,1.340000e+05,1.460000e+05
259,Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,"Yemen, Rep.",YEM,6.100000e+04,7.400000e+04,8.000000e+04,8.800000e+04,5.800000e+04,7.300000e+04,7.600000e+04,9.800000e+04,...,1.023000e+06,1.028000e+06,1.025000e+06,8.290000e+05,8.740000e+05,9.900000e+05,1.017500e+06,3.667000e+05,NaN,NaN
261,South Africa,ZAF,4.488000e+06,4.915000e+06,4.976000e+06,5.732000e+06,5.890000e+06,5.872000e+06,5.787000e+06,6.430000e+06,...,9.592000e+06,7.012000e+06,8.074000e+06,8.339000e+06,9.188000e+06,9.537000e+06,9.549000e+06,8.904000e+06,1.004400e+07,1.028500e+07
262,Zambia,ZMB,1.630000e+05,2.640000e+05,3.410000e+05,3.620000e+05,4.040000e+05,4.570000e+05,4.920000e+05,5.650000e+05,...,8.120000e+05,7.100000e+05,8.150000e+05,9.200000e+05,8.590000e+05,9.150000e+05,9.470000e+05,9.320000e+05,9.560000e+05,1.083000e+06
263,Zimbabwe,ZWE,1.416000e+06,1.597000e+06,1.336000e+06,2.090000e+06,2.250000e+06,1.967000e+06,2.217000e+06,2.041000e+06,...,1.956000e+06,2.017000e+06,2.239000e+06,2.423000e+06,1.794000e+06,1.833000e+06,1.880000e+06,2.057000e+06,2.168000e+06,2.423000e+06

In [13]:
# Read data from file 'Metadata_Country.csv' containing further information about countries

metadata_country=pd.read_csv('Metadata_Country.csv')

In [74]:
#Check the metadata_country data frame

metadata_country

,Country Code,Region,IncomeGroup,SpecialNotes,TableName
0,ABW,Latin America & Caribbean,High income,NaN,Aruba
1,AFG,South Asia,Low income,NaN,Afghanistan
2,AGO,Sub-Saharan Africa,Lower middle income,NaN,Angola
3,ALB,Europe & Central Asia,Upper middle income,NaN,Albania
4,AND,Europe & Central Asia,High income,NaN,Andorra
5,ARB,NaN,NaN,Arab World aggregate. Arab World is composed o...,Arab World
6,ARE,Middle East & North Africa,High income,NaN,United Arab Emirates
7,ARG,Latin America & Caribbean,Upper middle income,NaN,Argentina
8,ARM,Europe & Central Asia,Upper middle income,NaN,Armenia
9,ASM,East Asia & Pacific,Upper middle income,NaN,American Samoa
10,ATG,Latin America & Caribbean,High income,NaN,Antigua and Barbuda
11,AUS,East Asia & Pacific,High income,Fiscal year end: June 30; reporting period for...,Australia
12,AUT,Europe & Central Asia,High income,A simple multiplier is used to convert the nat...,Austria
13,AZE,Europe & Central Asia,Upper middle income,NaN,Azerbaijan
14,BDI,Sub-Saharan Africa,Low income,NaN,Burundi
15,BEL,Europe & Central Asia,High income,A simple multiplier is used to convert the nat...,Belgium
16,BEN,Sub-Saharan Africa,Low income,NaN,Benin
17,BFA,Sub-Saharan Africa,Low income,NaN,Burkina Faso
18,BGD,South Asia,Lower middle income,Fiscal year end: June 30; reporting period for...,Bangladesh
19,BGR,Europe & Central Asia,Upper middle income,NaN,Bulgaria
20,BHR,Middle East & North Africa,High income,NaN,Bahrain
21,BHS,Latin America & Caribbean,High income,NaN,"Bahamas, The"
22,BIH,Europe & Central Asia,Upper middle income,NaN,Bosnia and Herzegovina
23,BLR,Europe & Central Asia,Upper middle income,Data before 2015 were adjusted to reflect the ...,Belarus
24,BLZ,Latin America & Caribbean,Upper middle income,NaN,Belize
25,BMU,North America,High income,NaN,Bermuda
26,BOL,Latin America & Caribbean,Lower middle income,NaN,Bolivia
27,BRA,Latin America & Caribbean,Upper middle income,NaN,Brazil
28,BRB,Latin America & Caribbean,High income,NaN,Barbados
29,BRN,East Asia & Pacific,High income,NaN,Brunei Darussalam
...,...,...,...,...,...
233,TLA,NaN,NaN,Latin America & the Caribbean (IDA & IBRD coun...,Latin America & Caribbean (IDA & IBRD)
234,TLS,East Asia & Pacific,Lower middle income,NaN,Timor-Leste
235,TMN,NaN,NaN,Middle East & North Africa (IDA & IBRD countri...,Middle East & North Africa (IDA & IBRD)
236,TON,East Asia & Pacific,Upper middle income,NaN,Tonga
237,TSA,NaN,NaN,South Asia (IDA & IBRD countries) aggregate.,South Asia (IDA & IBRD)
238,TSS,NaN,NaN,Sub-Saharan Africa (IDA & IBRD countries) aggr...,Sub-Saharan Africa (IDA & IBRD)
239,TTO,Latin America & Caribbean,High income,NaN,Trinidad and Tobago
240,TUN,Middle East & North Africa,Lower middle income,NaN,Tunisia
241,TUR,Europe & Central Asia,Upper middle income,NaN,Turkey
242,TUV,East Asia & Pacific,Upper middle income,NaN,Tuvalu
243,TZA,Sub-Saharan Africa,Low income,NaN,Tanzania
244,UGA,Sub-Saharan Africa,Low income,Fiscal year end: June 30; reporting period for...,Uganda
245,UKR,Europe & Central Asia,Lower middle income,NaN,Ukraine
246,UMC,NaN,NaN,Upper middle income group aggregate. Upper-mid...,Upper middle income
247,URY,Latin America & Caribbean,High income,NaN,Uruguay
248,USA,North America,High income,NaN,United States
249,UZB,Europe & Central Asia,Lower middle income,NaN,Uzbekistan
250,VCT,Latin America & Caribbean,Upper middle income,NaN,St. Vincent and the Grenadines
251,VEN,Latin America & Caribbean,Upper middle income,NaN,"Venezuela, RB"
252,VGB,Latin America & Caribbean,High income,NaN,British Virgin Islands
253,VIR,Latin America & Caribbean,High income,NaN,Virgin Islands (U.S.)
254,VNM,East Asia & Pacific,Lower middle income,NaN,Vietnam
255,VUT,East Asia & Pacific,Lower middle income,NaN,Vanuatu
256,WLD,NaN,NaN,World aggregate.,World
257,WSM,East Asia & Pacific,Upper middle income,Fiscal year ends on June 30; reporting period ...,Samoa
258,XKX,Europe & Central Asia,Upper middle income,NaN,Kosovo
259,YEM,Middle East & North Africa,Low income,NaN,"Yemen, Rep."
260,ZAF,Sub-Saharan Africa,Upper middle income,Fiscal year end: March 31; reporting period fo...,South Africa
261,ZMB,Sub-Saharan Africa,Lower middle income,National accounts data were rebased to reflect...,Zambia
262,ZWE,Sub-Saharan Africa,Lower middle income,NaN,Zimbabwe

In [14]:
#Merge both data frames on 'Country Code' to have consolidate information an create a new data frame called df

df=arrivals.merge(metadata_country, on='Country Code', how='left')

arrivals

,Country Name,Country Code,1995,1996,1997,1998,1999,2000,2001,2002,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Aruba,ABW,6.190000e+05,6.410000e+05,6.500000e+05,6.470000e+05,6.830000e+05,7.210000e+05,6.910000e+05,6.430000e+05,...,8.270000e+05,8.130000e+05,8.240000e+05,8.690000e+05,9.040000e+05,9.790000e+05,1.072000e+06,1.225000e+06,1.102000e+06,1.070500e+06
1,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Angola,AGO,9.000000e+03,2.100000e+04,4.500000e+04,5.200000e+04,4.500000e+04,5.100000e+04,6.700000e+04,9.100000e+04,...,2.940000e+05,3.660000e+05,4.250000e+05,4.810000e+05,5.280000e+05,6.500000e+05,5.950000e+05,5.920000e+05,3.970000e+05,2.610000e+05
3,Albania,ALB,3.040000e+05,2.870000e+05,1.190000e+05,1.840000e+05,3.710000e+05,3.170000e+05,3.540000e+05,4.700000e+05,...,1.247000e+06,1.711000e+06,2.191000e+06,2.469000e+06,3.156000e+06,2.857000e+06,3.341000e+06,3.784000e+06,4.070000e+06,4.643000e+06
4,Andorra,AND,NaN,NaN,NaN,NaN,2.347000e+06,2.949000e+06,3.516000e+06,3.387000e+06,...,2.059000e+06,1.830000e+06,1.808000e+06,2.242000e+06,2.238000e+06,2.328000e+06,2.363000e+06,2.663000e+06,2.831000e+06,NaN
5,Arab World,ARB,2.115522e+07,2.192905e+07,2.384332e+07,2.623208e+07,3.010843e+07,3.391257e+07,3.478617e+07,3.904145e+07,...,7.456862e+07,7.372749e+07,8.459515e+07,7.090156e+07,7.899196e+07,7.869716e+07,8.415708e+07,7.885381e+07,7.636341e+07,8.221460e+07
6,United Arab Emirates,ARE,2.315000e+06,2.572000e+06,2.476000e+06,2.991000e+06,3.393000e+06,3.907000e+06,4.134000e+06,5.445000e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Argentina,ARG,2.289000e+06,2.614000e+06,2.764000e+06,3.012000e+06,2.898000e+06,2.909000e+06,2.620000e+06,2.820000e+06,...,4.700000e+06,4.308000e+06,5.325000e+06,5.705000e+06,5.587000e+06,5.246000e+06,5.931000e+06,5.736000e+06,6.655000e+06,6.720000e+06
8,Armenia,ARM,1.200000e+04,1.300000e+04,2.300000e+04,3.200000e+04,4.100000e+04,4.500000e+04,1.230000e+05,1.620000e+05,...,5.580000e+05,5.750000e+05,6.840000e+05,7.580000e+05,9.630000e+05,1.084000e+06,1.204000e+06,1.192000e+06,1.260000e+06,1.495000e+06
9,American Samoa,ASM,3.400000e+04,3.500000e+04,2.600000e+04,3.600000e+04,4.100000e+04,4.400000e+04,3.600000e+04,NaN,...,2.430000e+04,2.350000e+04,2.310000e+04,2.260000e+04,2.260000e+04,2.080000e+04,2.160000e+04,2.030000e+04,2.010000e+04,2.000000e+04
10,Antigua and Barbuda,ATG,2.200000e+05,2.280000e+05,2.400000e+05,2.340000e+05,2.320000e+05,2.070000e+05,2.150000e+05,2.180000e+05,...,2.660000e+05,2.340000e+05,2.300000e+05,2.410000e+05,2.470000e+05,2.430000e+05,2.490000e+05,2.500000e+05,2.650000e+05,2.470000e+05
11,Australia,AUS,3.726000e+06,4.165000e+06,4.318000e+06,4.167000e+06,4.459000e+06,4.931000e+06,4.856000e+06,4.841000e+06,...,5.586000e+06,5.490000e+06,5.790000e+06,5.771000e+06,6.032000e+06,6.482000e+06,6.922000e+06,7.450000e+06,8.269000e+06,8.815000e+06
12,Austria,AUT,1.717300e+07,1.709000e+07,1.664700e+07,1.735200e+07,1.746700e+07,1.798200e+07,1.818000e+07,1.861100e+07,...,2.193500e+07,2.135500e+07,2.200400e+07,2.301200e+07,2.415100e+07,2.481300e+07,2.529100e+07,2.672800e+07,2.812100e+07,2.946000e+07
13,Azerbaijan,AZE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.760000e+05,...,1.043000e+06,1.005000e+06,1.280000e+06,1.562000e+06,1.986000e+06,2.130000e+06,2.160000e+06,1.922000e+06,2.044000e+06,2.454000e+06
14,Burundi,BDI,3.400000e+04,2.700000e+04,1.100000e+04,1.500000e+04,2.600000e+04,2.900000e+04,3.600000e+04,7.400000e+04,...,2.020000e+05,2.120000e+05,1.420000e+05,1.440000e+05,1.470000e+05,2.340000e+05,2.350000e+05,1.310000e+05,1.870000e+05,2.990000e+05
15,Belgium,BEL,5.560000e+06,5.829000e+06,6.037000e+06,6.179000e+06,6.369000e+06,6.457000e+06,6.452000e+06,6.720000e+06,...,7.165000e+06,6.815000e+06,7.186000e+06,7.494000e+06,7.560000e+06,7.684000e+06,7.887000e+06,8.355000e+06,7.481000e+06,8.385000e+06
16,Benin,BEN,1.380000e+05,1.430000e+05,1.480000e+05,1.520000e+05,8.000000e+04,9.600000e+04,8.800000e+04,7.200000e+04,...,1.880000e+05,1.900000e+05,1.990000e+05,2.090000e+05,2.200000e+05,2.310000e+05,2.420000e+05,2.550000e+05,2.670000e+05,2.810000e+05
17,Burkina Faso,BFA,1.240000e+05,1.310000e+05,1.380000e+05,1.600000e+05,1.170000e+05,1.260000e+05,1.280000e+05,1.500000e+05,...,2.720000e+05,2.690000e+05,2.740000e+05,2.380000e+05,2.370000e+05,2.180000e+05,1.910000e+05,1.630000e+05,1.520000e+05,1.430000e+05
18,Bangladesh,BGD,1.560000e+05,1.660000e+05,1.820000e+05,1.720000e+05,1.730000e+05,1.990000e+05,2.070000e+05,2.070000e+05,...,4.670000e+05,2.670000e+05,3.030000e+05,1.550000e+05,1.250000e+05,1.480000e+05,1.250000e+05,NaN,NaN,NaN
19,Bulgaria,BGR,3.466000e+06,2.795000e+06,2.980000e+06,2.667000e+06,2.472000e+06,2.785000e+06,3.186000e+06,3.433000e+06,...,5.780000e+06,5.739000e+06,6.047000e+06,6.328000e+06,6.541000e+06,6.898000e+06,7.311000e+06,7.099000e+06,8.252000e+06,8.883000e+06
20,Bahrain,BHR,2.311000e+06,1.988000e+06,2.600000e+06,2.898000e+06,3.280000e+06,3.869000e+06,4.388000e+06,4.831000e+06,...,8.631000e+06,8.861000e+06,1.195200e+07,6.732000e+06,8.062000e+06,9.163000e+06,1.045200e+07,9.670000e+06,1.015800e+07,1.137000e+07
21,"Bahamas, The",BHS,1.598000e+06,1.633000e+06,1.618000e+06,1.528000e+06,1.577000e+06,1.544000e+06,1.538000e+06,1.513000e+06,...,1.463000e+06,1.327000e+06,1.370000e+06,1.346000e+06,1.422000e+06,1.366000e+06,1.427000e+06,1.484000e+06,1.499000e+06,1.439000e+06
22,Bosnia and Herzegovina,BIH,NaN,NaN,1.150000e+05,1.480000e+05,1.470000e+05,1.710000e+05,1.390000e+05,1.600000e+05,...,3.220000e+05,3.110000e+05,3.650000e+05,3.920000e+05,4.390000e+05,5.290000e+05,5.360000e+05,6.780000e+05,7.780000e+05,9.230000e+05
23,Belarus,BLR,1.606000e+05,2.340000e+05,2.535000e+05,3.550000e+05,7.490000e+04,6.000000e+04,6.100000e+04,6.300000e+04,...,9.050000e+04,9.500000e+04,1.193000e+05,1.160000e+05,6.129900e+06,6.241800e+06,5.374900e+06,4.385600e+06,1.093540e+07,1.106020e+07
24,Belize,BLZ,1.310000e+05,1.330000e+05,1.460000e+05,1.760000e+05,1.810000e+05,1.960000e+05,1.960000e+05,2.000000e+05,...,2.450000e+05,2.320000e+05,2.420000e+05,2.500000e+05,2.770000e+05,2.940000e+05,3.210000e+05,3.410000e+05,3.860000e+05,4.270000e+05
25,Bermuda,BMU,3.870000e+05,3.900000e+05,3.800000e+05,3.700000e+05,3.550000e+05,3.320000e+05,2.780000e+05,2.840000e+05,...,2.640000e+05,2.360000e+05,2.320000e+05,2.360000e+05,2.320000e+05,2.360000e+05,2.240000e+05,2.200000e+05,2.440000e+05,2.700000e+05
26,Bolivia,BOL,2.840000e+05,3.130000e+05,3.550000e+05,3.870000e+05,3.420000e+05,3.190000e+05,3.160000e+05,3.340000e+05,...,5.940000e+05,5.990000e+05,6.790000e+05,7.110000e+05,7.980000e+05,7.980000e+05,8.710000e+05,8.820000e+05,9.590000e+05,1.134000e+06
27,Brazil,BRA,1.991000e+06,2.666000e+06,2.850000e+06,4.818000e+06,5.107000e+06,5.313000e+06,4.773000e+06,3.785000e+06,...,5.050000e+06,4.802000e+06,5.161000e+06,5.433000e+06,5.677000e+06,5.813000e+06,6.430000e+06,6.306000e+06,6.547000e+06,6.589000e+06
28,Barbados,BRB,4.420000e+05,4.470000e+05,4.720000e+05,5.120000e+05,5.150000e+05,5.450000e+05,5.070000e+05,4.980000e+05,...,5.680000e+05,5.190000e+05,5.320000e+05,5.680000e+05,5.360000e+05,5.090000e+05,5.210000e+05,5.920000e+05,6.320000e+05,6.640000e+05
29,Brunei Darussalam,BRN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.260000e+05,1.570000e+05,2.140000e+05,2.420000e+05,2.090000e+05,2.250000e+05,2.010000e+05,2.180000e+05,2.190000e+05,2.590000e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Latin America & the Caribbean (IDA & IBRD coun...,TLA,3.866900e+07,4.055500e+07,4.014200e+07,4.289600e+07,4.307600e+07,4.580400e+07,4.420500e+07,4.240700e+07,...,6.054600e+07,5.873000e+07,6.136500e+07,6.495000e+07,6.732700e+07,6.889840e+07,7.719810e+07,8.303000e+07,8.976419e+07,9.818026e+07
235,Timor-Leste,TLS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.600000e+04,4.400000e+04,4.000000e+04,5.100000e+04,5.800000e+04,7.900000e+04,6.000000e+04,6.200000e+04,6.600000e+04,7.400000e+04
236,Middle East & North Africa (IDA & IBRD countries),TMN,1.362004e+07,1.439085e+07,1.570795e+07,1.722888e+07,1.983101e+07,2.198938e+07,2.209232e+07,2.406148e+07,...,4.431138e+07,4.705281e+07,5.473675e+07,4.426041e+07,4.803150e+07,4.760095e+07,4.810056e+07,4.403788e+07,4.003877e+07,4.723084e+07
237,Tonga,TON,2.900000e+04,2.700000e+04,2.600000e+04,2.700000e+04,3.100000e+04,3.500000e+04,3.200000e+04,3.700000e+04,...,5.000000e+04,4.570000e+04,4.710000e+04,4.600000e+04,4.740000e+04,4.820000e+04,5.040000e+04,5.380000e+04,5.910000e+04,6.250000e+04
238,South Asia (IDA & IBRD),TSA,3.809177e+06,3.930662e+06,4.161829e+06,4.280669e+06,4.529947e+06,4.826436e+06,4.486400e+06,4.321774e+06,...,8.365578e+06,8.065426e+06,9.234491e+06,1.039236e+07,1.072507e+07,1.168277e+07,1.891533e+07,1.919519e+07,2.129414e+07,2.284510e+07
239,Sub-Saharan Africa (IDA & IBRD countries),TSS,1.295720e+07,1.474029e+07,1.469061e+07,1.665619e+07,1.731444e+07,1.757944e+07,1.812036e+07,1.941256e+07,...,3.060059e+07,2.833533e+07,3.145731e+07,3.310224e+07,3.426820e+07,3.546457e+07,3.677882e+07,3.718509e+07,4.069832e+07,4.236450e+07
240,Trinidad and Tobago,TTO,2.600000e+05,2.660000e+05,3.240000e+05,3.340000e+05,3.580000e+05,3.990000e+05,3.830000e+05,3.840000e+05,...,4.370000e+05,4.190000e+05,3.880000e+05,4.310000e+05,4.550000e+05,4.340000e+05,4.120000e+05,4.400000e+05,4.090000e+05,3.950000e+05
241,Tunisia,TUN,4.120000e+06,3.885000e+06,4.263000e+06,4.718000e+06,4.832000e+06,5.058000e+06,5.387000e+06,5.064000e+06,...,7.050000e+06,7.797000e+06,7.828000e+06,5.746000e+06,6.999000e+06,7.352000e+06,7.163000e+06,5.359000e+06,5.724000e+06,7.052000e+06
242,Turkey,TUR,7.083000e+06,7.966000e+06,9.040000e+06,8.960000e+06,6.893000e+06,9.586000e+06,1.078300e+07,1.279000e+07,...,2.979200e+07,3.018700e+07,3.136400e+07,3.465400e+07,3.569800e+07,3.779500e+07,3.981100e+07,3.947800e+07,3.028900e+07,3.760100e+07
243,Tuvalu,TUV,9.000000e+02,1.000000e+03,1.000000e+03,1.000000e+03,1.100000e+03,1.100000e+03,1.100000e+03,1.300000e+03,...,1.700000e+03,1.600000e+03,1.700000e+03,1.200000e+03,1.100000e+03,1.300000e+03,1.400000e+03,2.400000e+03,2.500000e+03,2.500000e+03
244,Tanzania,TZA,2.850000e+05,3.150000e+05,3.470000e+05,4.500000e+05,5.640000e+05,4.590000e+05,5.010000e+05,5.500000e+05,...,7.500000e+05,6.950000e+05,7.540000e+05,8.430000e+05,1.043000e+06,1.063000e+06,1.113000e+06,1.104000e+06,1.233000e+06,1.275000e+06
245,Uganda,UGA,1.600000e+05,1.740000e+05,1.750000e+05,1.950000e+05,1.890000e+05,1.930000e+05,2.050000e+05,2.540000e+05,...,8.440000e+05,8.070000e+05,9.460000e+05,1.151000e+06,1.197000e+06,1.206000e+06,1.266000e+06,1.303000e+06,1.323000e+06,1.402000e+06
246,Ukraine,UKR,3.716000e+06,3.854000e+06,7.558000e+06,6.208000e+06,4.232000e+06,6.431000e+06,9.174000e+06,1.051700e+07,...,2.544900e+07,2.079800e+07,2.120300e+07,2.141500e+07,2.301300e+07,2.467100e+07,1.271200e+07,1.242800e+07,1.333300e+07,1.423000e+07
247,Upper middle income,UMC,1.065449e+08,1.181832e+08,1.206538e+08,1.251263e+08,1.323729e+08,1.495985e+08,1.561402e+08,1.672680e+08,...,2.472731e+08,2.397889e+08,2.576097e+08,2.759217e+08,2.971059e+08,3.098793e+08,3.227713e+08,3.332267e+08,3.382353e+08,3.635761e+08
248,Uruguay,URY,2.022000e+06,2.152000e+06,2.316000e+06,2.163000e+06,2.073000e+06,1.968000e+06,1.892000e+06,1.258000e+06,...,1.938000e+06,2.055000e+06,2.353000e+06,2.857000e+06,2.695000e+06,2.683000e+06,2.682000e+06,2.773000e+06,3.037000e+06,3.674000e+06
249,United States,USA,4.331800e+07,4.648900e+07,4.776700e+07,4.637700e+07,4.850900e+07,5.123800e+07,4.692700e+07,4.358100e+07,...,5.800700e+07,5.510300e+07,6.001000e+07,6.282100e+07,6.665700e+07,6.999500e+07,7.502200e+07,7.777400e+07,7.640700e+07,7.694100e+07
250,Uzbekistan,UZB,9.200000e+04,1.730000e+05,9.600000e+05,8.110000e+05,4.870000e+05,3.020000e+05,3.450000e+05,3.320000e+05,...,1.069000e+06,1.215000e+06,9.750000e+05,NaN,NaN,1.969000e+06,1.862000e+06,1.918000e+06,2.027000e+06,2.690000e+06
251,St. Vincent and the Grenadines,VCT,6.000000e+04,5.800000e+04,6.500000e+04,6.700000e+04,6.800000e+04,7.300000e+04,7.100000e+04,7.800000e+04,...,8.400000e+04,7.500000e+04,7.200000e+04,7.400000e+04,7.400000e+04,7.200000e+04,7.100000e+04,7.500000e+04,7.900000e+04,7.600000e+04
252,"Venezuela, RB",VEN,7.000000e+05,7.590000e+05,8.140000e+05,6.850000e+05,5.870000e+05,4.690000e+05,5.840000e+05,4.320000e+05,...,6.990000e+05,5.620000e+05,5.260000e+05,5.950000e+05,9.880000e+05,9.860000e+05,8.570000e+05,7.890000e+05,6.010000e+05,4.270000e+05
253,British Virgin Islands,VGB,2.190000e+05,2.440000e+05,2.440000e+05,2.790000e+05,2.840000e+05,2.720000e+05,2.960000e+05,2.820000e+05,...,3.460000e+05,3.090000e+05,3.300000e+05,3.380000e+05,3.510000e+05,3.660000e+05,3.860000e+05,3.930000e+05,4.080000e+05,3.350000e+05
254,Virgin Islands (U.S.),VIR,4.540000e+05,3.730000e+05,3.930000e+05,4.220000e+05,4.840000e+05,5.460000e+05,5.270000e+05,5.200000e+05,...,5.740000e+05,5.630000e+05,5.720000e+05,5.670000e+05,6.190000e+05,5.900000e+05,6.150000e+05,6.420000e+05,6.670000e+05,NaN
255,Vietnam,VNM,1.351000e+06,1.607000e+06,1.716000e+06,1.520000e+06,1.782000e+06,2.140000e+06,2.330000e+06,2.628000e+06,...,4.236000e+06,3.747000e+06,5.050000e+06,6.014000e+06,6.848000e+06,7.572000e+06,7.874000e+06,7.944000e+06,1.001300e+07,1.292200e+07
256,Vanuatu,VUT,4.400000e+04,4.600000e+04,5.000000e+04,5.200000e+04,5.100000e+04,5.800000e+04,5.300000e+04,4.900000e+04,...,9.050000e+04,1.007000e+05,9.720000e+04,9.400000e+04,1.082000e+05,1.100000e+05,1.090000e+05,9.000000e+04,9.510000e+04,1.090000e+05
257,World,WLD,5.239096e+08,5.545516e+08,5.843048e+08,6.022473e+08,6.272079e+08,6.773870e+08,6.782462e+08,6.984316e+08,...,9.363609e+08,8.975338e+08,9.563723e+08,9.975553e+08,1.054602e+09,1.106732e+09,1.159450e+09,1.206216e+09,1.250468e+09,1.341457e+09
258,Samoa,WSM,6.800000e+04,7.300000e+04,6.800000e+04,7.800000e+04,8.500000e+04,8.800000e+04,8.800000e+04,8.900000e+04,...,1.180000e+05,1.220000e+05,1.220000e+05,1.210000e+05,1.260000e+05,1.160000e+05,1.204000e+05,1.280000e+05,1.340000e+05,1.460000e+05
259,Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,"Yemen, Rep.",YEM,6.100000e+04,7.400000e+04,8.000000e+04,8.800000e+04,5.800000e+04,7.300000e+04,7.600000e+04,9.800000e+04,...,1.023000e+06,1.028000e+06,1.025000e+06,8.290000e+05,8.740000e+05,9.900000e+05,1.017500e+06,3.667000e+05,NaN,NaN
261,South Africa,ZAF,4.488000e+06,4.915000e+06,4.976000e+06,5.732000e+06,5.890000e+06,5.872000e+06,5.787000e+06,6.430000e+06,...,9.592000e+06,7.012000e+06,8.074000e+06,8.339000e+06,9.188000e+06,9.537000e+06,9.549000e+06,8.904000e+06,1.004400e+07,1.028500e+07
262,Zambia,ZMB,1.630000e+05,2.640000e+05,3.410000e+05,3.620000e+05,4.040000e+05,4.570000e+05,4.920000e+05,5.650000e+05,...,8.120000e+05,7.100000e+05,8.150000e+05,9.200000e+05,8.590000e+05,9.150000e+05,9.470000e+05,9.320000e+05,9.560000e+05,1.083000e+06
263,Zimbabwe,ZWE,1.416000e+06,1.597000e+06,1.336000e+06,2.090000e+06,2.250000e+06,1.967000e+06,2.217000e+06,2.041000e+06,...,1.956000e+06,2.017000e+06,2.239000e+06,2.423000e+06,1.794000e+06,1.833000e+06,1.880000e+06,2.057000e+06,2.168000e+06,2.423000e+06

In [15]:
#Check the first rows of the new data frame

df.head()

,Country Name,Country Code,1995,1996,1997,1998,1999,2000,2001,2002,...,2013,2014,2015,2016,2017,Region,IncomeGroup,SpecialNotes,TableName,Unnamed: 5
0,Aruba,ABW,619000.0,641000.0,650000.0,647000.0,683000.0,721000.0,691000.0,643000.0,...,979000.0,1072000.0,1225000.0,1102000.0,1070500.0,Latin America & Caribbean,High income,NaN,Aruba,NaN
1,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,South Asia,Low income,NaN,Afghanistan,NaN
2,Angola,AGO,9000.0,21000.0,45000.0,52000.0,45000.0,51000.0,67000.0,91000.0,...,650000.0,595000.0,592000.0,397000.0,261000.0,Sub-Saharan Africa,Lower middle income,NaN,Angola,NaN
3,Albania,ALB,304000.0,287000.0,119000.0,184000.0,371000.0,317000.0,354000.0,470000.0,...,2857000.0,3341000.0,3784000.0,4070000.0,4643000.0,Europe & Central Asia,Upper middle income,NaN,Albania,NaN
4,Andorra,AND,NaN,NaN,NaN,NaN,2347000.0,2949000.0,3516000.0,3387000.0,...,2328000.0,2363000.0,2663000.0,2831000.0,NaN,Europe & Central Asia,High income,NaN,Andorra,NaN

In [16]:
#Check our countries

df[df['TableName']=='Colombia']

,Country Name,Country Code,1995,1996,1997,1998,1999,2000,2001,2002,...,2013,2014,2015,2016,2017,Region,IncomeGroup,SpecialNotes,TableName,Unnamed: 5
43,Colombia,COL,1399000.0,631000.0,639000.0,674000.0,546000.0,557000.0,616000.0,567000.0,...,2288000.0,2552000.0,2978000.0,3317000.0,4113000.0,Latin America & Caribbean,Upper middle income,NaN,Colombia,NaN

In [17]:
df[df['TableName']=='Brazil']

,Country Name,Country Code,1995,1996,1997,1998,1999,2000,2001,2002,...,2013,2014,2015,2016,2017,Region,IncomeGroup,SpecialNotes,TableName,Unnamed: 5
27,Brazil,BRA,1991000.0,2666000.0,2850000.0,4818000.0,5107000.0,5313000.0,4773000.0,3785000.0,...,5813000.0,6430000.0,6306000.0,6547000.0,6589000.0,Latin America & Caribbean,Upper middle income,NaN,Brazil,NaN

In [18]:
df[df['TableName']=='Cambodia']

,Country Name,Country Code,1995,1996,1997,1998,1999,2000,2001,2002,...,2013,2014,2015,2016,2017,Region,IncomeGroup,SpecialNotes,TableName,Unnamed: 5
121,Cambodia,KHM,220000.0,260000.0,219000.0,287000.0,368000.0,466000.0,605000.0,787000.0,...,4210000.0,4503000.0,4775000.0,5012000.0,5602000.0,East Asia & Pacific,Lower middle income,NaN,Cambodia,NaN

In [19]:
df[df['TableName']=='Portugal']

,Country Name,Country Code,1995,1996,1997,1998,1999,2000,2001,2002,...,2013,2014,2015,2016,2017,Region,IncomeGroup,SpecialNotes,TableName,Unnamed: 5
192,Portugal,PRT,4572000.0,4567000.0,4798000.0,5539000.0,5379000.0,5599000.0,5392000.0,5560000.0,...,9177000.0,10497000.0,11723000.0,13359000.0,15432000.0,Europe & Central Asia,High income,A simple multiplier is used to convert the nat...,Portugal,NaN

In [20]:
#Find the top 10 countries or regions with the most number of visitor in 2017

df.nlargest(10, ['2017'])

,Country Name,Country Code,1995,1996,1997,1998,1999,2000,2001,2002,...,2013,2014,2015,2016,2017,Region,IncomeGroup,SpecialNotes,TableName,Unnamed: 5
257,World,WLD,5.239096e+08,5.545516e+08,5.843048e+08,6.022473e+08,6.272079e+08,6.773870e+08,6.782462e+08,6.984316e+08,...,1.106732e+09,1.159450e+09,1.206216e+09,1.250468e+09,1.341457e+09,NaN,NaN,World aggregate.,World,NaN
93,High income,HIC,3.788522e+08,3.936993e+08,4.145348e+08,4.285978e+08,4.448873e+08,4.722706e+08,4.639270e+08,4.699728e+08,...,6.584570e+08,6.995938e+08,7.330564e+08,7.686113e+08,8.147399e+08,NaN,NaN,High income group aggregate. High-income econo...,High income,NaN
179,OECD members,OED,3.585940e+08,3.731950e+08,3.908013e+08,4.035437e+08,4.151737e+08,4.402514e+08,4.293773e+08,4.332865e+08,...,5.921553e+08,6.302726e+08,6.641770e+08,6.873700e+08,7.387490e+08,NaN,NaN,Aggregations include Lithuania.,OECD members,NaN
196,Post-demographic dividend,PST,3.291888e+08,3.429809e+08,3.659201e+08,3.780410e+08,3.909029e+08,4.177407e+08,4.143457e+08,4.218814e+08,...,5.987758e+08,6.194239e+08,6.475276e+08,6.862630e+08,7.311272e+08,NaN,NaN,Post-dividend countries are mostly high-income...,Post-demographic dividend,NaN
63,Europe & Central Asia,ECS,2.955132e+08,3.116283e+08,3.366543e+08,3.468680e+08,3.551063e+08,3.830515e+08,3.841048e+08,3.954744e+08,...,5.677226e+08,5.797844e+08,6.038805e+08,6.159794e+08,6.695441e+08,NaN,NaN,Europe and Central Asia regional aggregate (in...,Europe & Central Asia,NaN
101,IDA & IBRD total,IBT,1.661324e+08,1.830733e+08,1.935366e+08,1.965972e+08,2.030591e+08,2.269594e+08,2.348990e+08,2.476356e+08,...,4.749737e+08,4.869817e+08,5.027129e+08,5.136785e+08,5.615830e+08,NaN,NaN,IDA and IBRD total group aggregate (includes I...,IDA & IBRD total,NaN
71,European Union,EUU,2.587999e+08,2.677640e+08,2.850780e+08,2.970440e+08,3.068010e+08,3.248400e+08,3.203740e+08,3.259980e+08,...,4.212660e+08,4.421430e+08,4.637260e+08,4.846420e+08,5.226200e+08,NaN,NaN,European Union aggregate.,European Union,NaN
138,Low & middle income,LMY,1.419560e+08,1.574997e+08,1.662356e+08,1.700167e+08,1.785592e+08,2.012201e+08,2.107233e+08,2.250193e+08,...,4.441156e+08,4.552279e+08,4.681974e+08,4.764683e+08,5.213047e+08,NaN,NaN,NaN,Low & middle income,NaN
154,Middle income,MIC,1.364637e+08,1.513786e+08,1.597886e+08,1.631518e+08,1.714744e+08,1.930651e+08,2.023099e+08,2.156159e+08,...,4.214041e+08,4.320154e+08,4.453550e+08,4.528075e+08,4.957631e+08,NaN,NaN,Middle income group aggregate. Middle-income e...,Middle income,NaN
100,IBRD only,IBD,1.533753e+08,1.685863e+08,1.780072e+08,1.797196e+08,1.856425e+08,2.085053e+08,2.156061e+08,2.269882e+08,...,4.223739e+08,4.317754e+08,4.437688e+08,4.538836e+08,4.956879e+08,NaN,NaN,IBRD only group aggregate.,IBRD only,NaN

In [21]:
#Find the top 10 countries exclusively with the most number of visitor in 2017. 
#We need to exclude Regions and Income Groups to look only for countries data

df[(df['Region'].notnull()) & (df['IncomeGroup'].notnull())].nlargest(10,['2017'])

,Country Name,Country Code,1995,1996,1997,1998,1999,2000,2001,2002,...,2013,2014,2015,2016,2017,Region,IncomeGroup,SpecialNotes,TableName,Unnamed: 5
75,France,FRA,60033000.0,62406000.0,66591000.0,70109000.0,73147000.0,77190000.0,75202000.0,77012000.0,...,83634000.0,83701000.0,84452000.0,82682000.0,86861000.0,Europe & Central Asia,High income,The following irrevocable euro conversion rate...,France,NaN
68,Spain,ESP,32971000.0,34027000.0,39553000.0,41892000.0,45440000.0,46403000.0,48565000.0,50331000.0,...,60675000.0,64939000.0,68175000.0,75315000.0,81786000.0,Europe & Central Asia,High income,A simple multiplier is used to convert the nat...,Spain,NaN
249,United States,USA,43318000.0,46489000.0,47767000.0,46377000.0,48509000.0,51238000.0,46927000.0,43581000.0,...,69995000.0,75022000.0,77774000.0,76407000.0,76941000.0,North America,High income,NaN,United States,NaN
38,China,CHN,20034000.0,22765000.0,23770000.0,25073000.0,27047000.0,31229000.0,33167000.0,36803000.0,...,55686000.0,55622000.0,56886000.0,59270000.0,60740000.0,East Asia & Pacific,Upper middle income,On 1 July 1997 China resumed its exercise of s...,China,NaN
114,Italy,ITA,31052000.0,32943000.0,34692000.0,34933000.0,36516000.0,41181000.0,39563000.0,39799000.0,...,47704000.0,48576000.0,50732000.0,52372000.0,58253000.0,Europe & Central Asia,High income,A simple multiplier is used to convert the nat...,Italy,NaN
152,Mexico,MEX,20241000.0,21395000.0,19351000.0,19392000.0,19043000.0,20641000.0,19810000.0,19667000.0,...,24151000.0,29346000.0,32093000.0,35079000.0,39291000.0,Latin America & Caribbean,Upper middle income,NaN,Mexico,NaN
79,United Kingdom,GBR,21719000.0,22936000.0,23215000.0,23710000.0,23341000.0,23212000.0,20982000.0,22307000.0,...,31063000.0,32613000.0,34436000.0,35814000.0,37651000.0,Europe & Central Asia,High income,NaN,United Kingdom,NaN
242,Turkey,TUR,7083000.0,7966000.0,9040000.0,8960000.0,6893000.0,9586000.0,10783000.0,12790000.0,...,37795000.0,39811000.0,39478000.0,30289000.0,37601000.0,Europe & Central Asia,Upper middle income,NaN,Turkey,NaN
53,Germany,DEU,14847000.0,15205000.0,15837000.0,16511000.0,17116000.0,18983000.0,17861000.0,17969000.0,...,31545000.0,32999000.0,34970000.0,35555000.0,37452000.0,Europe & Central Asia,High income,NaN,Germany,NaN
231,Thailand,THA,6952000.0,7244000.0,7294000.0,7843000.0,8651000.0,9579000.0,10133000.0,10873000.0,...,26547000.0,24810000.0,29923000.0,32530000.0,35592000.0,East Asia & Pacific,Upper middle income,Fiscal year end: September 30; reporting perio...,Thailand,NaN

In [22]:
#Find the bottom 10 only countries exclusively with the most number of visitor in 2017. 

df[(df['Region'].notnull()) & (df['IncomeGroup'].notnull())].nsmallest(10,['2017'])

,Country Name,Country Code,1995,1996,1997,1998,1999,2000,2001,2002,...,2013,2014,2015,2016,2017,Region,IncomeGroup,SpecialNotes,TableName,Unnamed: 5
243,Tuvalu,TUV,900.0,1000.0,1000.0,1000.0,1100.0,1100.0,1100.0,1300.0,...,1300.0,1400.0,2400.0,2500.0,2500.0,East Asia & Pacific,Upper middle income,NaN,Tuvalu,NaN
122,Kiribati,KIR,3900.0,4200.0,5100.0,5700.0,5100.0,4800.0,4600.0,4900.0,...,5900.0,5000.0,3900.0,5700.0,5800.0,East Asia & Pacific,Lower middle income,NaN,Kiribati,NaN
153,Marshall Islands,MHL,5500.0,6200.0,6400.0,6400.0,4600.0,5200.0,5400.0,6000.0,...,NaN,4900.0,6300.0,5400.0,6000.0,East Asia & Pacific,Upper middle income,Fiscal year ends on September 30; reporting pe...,Marshall Islands,NaN
9,American Samoa,ASM,34000.0,35000.0,26000.0,36000.0,41000.0,44000.0,36000.0,NaN,...,20800.0,21600.0,20300.0,20100.0,20000.0,East Asia & Pacific,Upper middle income,NaN,American Samoa,NaN
207,Solomon Islands,SLB,11800.0,10300.0,13800.0,15800.0,NaN,5200.0,NaN,NaN,...,24400.0,20100.0,21600.0,23200.0,25700.0,East Asia & Pacific,Lower middle income,NaN,Solomon Islands,NaN
44,Comoros,COM,23000.0,24000.0,26000.0,27000.0,24000.0,24000.0,19400.0,18900.0,...,21900.0,22800.0,23600.0,26800.0,28000.0,Sub-Saharan Africa,Lower middle income,NaN,Comoros,NaN
237,Tonga,TON,29000.0,27000.0,26000.0,27000.0,31000.0,35000.0,32000.0,37000.0,...,48200.0,50400.0,53800.0,59100.0,62500.0,East Asia & Pacific,Upper middle income,NaN,Tonga,NaN
135,Liechtenstein,LIE,59000.0,56000.0,57000.0,59000.0,60000.0,61600.0,56500.0,48700.0,...,52400.0,53700.0,48600.0,60000.0,69000.0,Europe & Central Asia,High income,NaN,Liechtenstein,NaN
55,Dominica,DMA,60000.0,63000.0,65000.0,66000.0,74000.0,70000.0,66000.0,69000.0,...,78000.0,81500.0,75000.0,78000.0,72000.0,Latin America & Caribbean,Upper middle income,NaN,Dominica,NaN
235,Timor-Leste,TLS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,79000.0,60000.0,62000.0,66000.0,74000.0,East Asia & Pacific,Lower middle income,NaN,Timor-Leste,NaN

In [30]:
df['Growth5ys']=(df['2017']/df['2012']-1)
df['Growth10ys']=(df['2017']/df['2007']-1)

In [37]:
df[df['Region'].notnull()].nlargest(10,['Growth5ys'])

,Country Name,Country Code,1995,1996,1997,1998,1999,2000,2001,2002,...,2015,2016,2017,Region,IncomeGroup,SpecialNotes,TableName,Unnamed: 5,Growth5ys,Growth10ys
39,Cote d'Ivoire,CIV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1441000.0,1583000.0,1800000.0,Sub-Saharan Africa,Lower middle income,NaN,Côte d'Ivoire,NaN,5.228374,8.890110
117,Japan,JPN,3345000.0,3837000.0,4218000.0,4106000.0,4438000.0,4757000.0,4772000.0,5239000.0,...,19737000.0,24040000.0,28691000.0,East Asia & Pacific,High income,Fiscal year end: March 31; reporting period fo...,Japan,NaN,2.432759,2.437283
112,Iceland,ISL,190000.0,201000.0,202000.0,232000.0,263000.0,303000.0,301000.0,285000.0,...,1289000.0,1792000.0,2225000.0,Europe & Central Asia,High income,NaN,Iceland,NaN,2.306092,3.587629
158,Myanmar,MMR,194000.0,490000.0,491000.0,478000.0,435000.0,416000.0,475000.0,487000.0,...,4681000.0,2907000.0,3443000.0,East Asia & Pacific,Lower middle income,Fiscal year end: March 31; reporting period fo...,Myanmar,NaN,2.251180,3.808659
193,Paraguay,PRY,438000.0,426000.0,395000.0,350000.0,269000.0,289000.0,279000.0,250000.0,...,1215000.0,1308000.0,1584000.0,Latin America & Caribbean,Upper middle income,NaN,Paraguay,NaN,1.735751,2.807692
139,Lesotho,LSO,209000.0,312000.0,313000.0,290000.0,308000.0,302000.0,295000.0,287000.0,...,1082000.0,1196000.0,1137000.0,Sub-Saharan Africa,Lower middle income,Fiscal year end: March 31; reporting period fo...,Lesotho,NaN,1.687943,2.790000
30,Bhutan,BTN,4800.0,5200.0,5400.0,6200.0,7200.0,7600.0,6400.0,5600.0,...,155000.0,210000.0,255000.0,South Asia,Lower middle income,NaN,Bhutan,NaN,1.428571,11.142857
107,India,IND,2124000.0,2288000.0,2374000.0,2359000.0,2482000.0,2649000.0,2537000.0,2384000.0,...,13284000.0,14570000.0,15543000.0,South Asia,Lower middle income,Fiscal year end: March 31; reporting period fo...,India,NaN,1.362876,2.058442
243,Tuvalu,TUV,900.0,1000.0,1000.0,1000.0,1100.0,1100.0,1100.0,1300.0,...,2400.0,2500.0,2500.0,East Asia & Pacific,Upper middle income,NaN,Tuvalu,NaN,1.272727,1.272727
230,Togo,TGO,53000.0,58000.0,92000.0,69000.0,70000.0,60000.0,57000.0,58000.0,...,273000.0,338000.0,496000.0,Sub-Saharan Africa,Low income,NaN,Togo,NaN,1.110638,4.767442

In [67]:
df.loc[df['Region'].notnull(),['Country Name','Growth5ys','Growth10ys']].nlargest(10,'Growth5ys')

      Country Name  Growth5ys  Growth10ys
39   Cote d'Ivoire   5.228374    8.890110
117          Japan   2.432759    2.437283
112        Iceland   2.306092    3.587629
158        Myanmar   2.251180    3.808659
193       Paraguay   1.735751    2.807692
139        Lesotho   1.687943    2.790000
30          Bhutan   1.428571   11.142857
107          India   1.362876    2.058442
243         Tuvalu   1.272727    1.272727
230           Togo   1.110638    4.767442

In [125]:
df1= df[['Country Name','Country Code']]

In [137]:
x=1996
while x<2018:
    df1.loc[:,str(x)]=((df.loc[:,str(x)]-df.loc[:,str(x-1)])/df.loc[:,str(x)])
    x+=1

In [136]:
df1

,Country Name,Country Code,1996,1997,1998,1999,2000,2001,2002,2003,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Aruba,ABW,0.034321,0.013846,-0.004637,0.052709,0.052705,-0.043415,-0.074650,-0.001558,...,0.066505,-0.017220,0.013350,0.051784,0.038717,0.076609,0.086754,0.124898,-0.111615,-0.029426
1,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Angola,AGO,0.571429,0.533333,0.134615,-0.155556,0.117647,0.238806,0.263736,0.149533,...,0.336735,0.196721,0.138824,0.116424,0.089015,0.187692,-0.092437,-0.005068,-0.491184,-0.521073
3,Albania,ALB,-0.059233,-1.411765,0.353261,0.504043,-0.170347,0.104520,0.246809,0.156194,...,0.148356,0.271186,0.219078,0.112596,0.217681,-0.104655,0.144867,0.117072,0.070270,0.123412
4,Andorra,AND,NaN,NaN,NaN,NaN,0.204137,0.161263,-0.038087,-0.079350,...,-0.063137,-0.125137,-0.012168,0.193577,-0.001787,0.038660,0.014812,0.112655,0.059343,NaN
5,Arab World,ARB,0.035288,0.080286,0.091063,0.128746,0.112175,0.025113,0.108994,0.043372,...,0.134861,-0.011409,0.128467,-0.193135,0.102420,-0.003746,0.064878,-0.067254,-0.032613,0.071170
6,United Arab Emirates,ARE,0.099922,-0.038772,0.172183,0.118479,0.131559,0.054910,0.240771,0.072560,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Argentina,ARG,0.124331,0.054269,0.082337,-0.039337,0.003781,-0.110305,0.070922,0.058431,...,0.029362,-0.090994,0.190986,0.066608,-0.021120,-0.065002,0.115495,-0.033996,0.138092,0.009673
8,Armenia,ARM,0.076923,0.434783,0.281250,0.219512,0.088889,0.634146,0.240741,0.213592,...,0.084229,0.029565,0.159357,0.097625,0.212876,0.111624,0.099668,-0.010067,0.053968,0.157191
9,American Samoa,ASM,0.028571,-0.346154,0.277778,0.121951,0.068182,-0.222222,NaN,NaN,...,0.008230,-0.034043,-0.017316,-0.022124,0.000000,-0.086538,0.037037,-0.064039,-0.009950,-0.005000
10,Antigua and Barbuda,ATG,0.035088,0.050000,-0.025641,-0.008621,-0.120773,0.037209,0.013761,0.087866,...,0.015038,-0.136752,-0.017391,0.045643,0.024291,-0.016461,0.024096,0.004000,0.056604,-0.072874
11,Australia,AUS,0.105402,0.035433,-0.036237,0.065486,0.095721,-0.015445,-0.003099,-0.020017,...,-0.010383,-0.017486,0.051813,-0.003292,0.043269,0.069423,0.063565,0.070872,0.099045,0.061940
12,Austria,AUT,-0.004857,-0.026611,0.040629,0.006584,0.028640,0.010891,0.023158,0.024478,...,0.052975,-0.027160,0.029495,0.043803,0.047162,0.026680,0.018900,0.053764,0.049536,0.045451
13,Azerbaijan,AZE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.250000,...,0.298178,-0.037811,0.214844,0.180538,0.213494,0.067606,0.013889,-0.123829,0.059687,0.167074
14,Burundi,BDI,-0.259259,-1.454545,0.266667,0.423077,0.103448,0.194444,0.513514,0.000000,...,0.049505,0.047170,-0.492958,0.013889,0.020408,0.371795,0.004255,-0.793893,0.299465,0.374582
15,Belgium,BEL,0.046149,0.034454,0.022981,0.029832,0.013629,-0.000775,0.039881,-0.004484,...,0.016748,-0.051357,0.051628,0.041100,0.008730,0.016137,0.025739,0.056014,-0.116829,0.107812
16,Benin,BEN,0.034965,0.033784,0.026316,-0.900000,0.166667,-0.090909,-0.222222,0.588571,...,0.010638,0.010526,0.045226,0.047847,0.050000,0.047619,0.045455,0.050980,0.044944,0.049822
17,Burkina Faso,BFA,0.053435,0.050725,0.137500,-0.367521,0.071429,0.015625,0.146667,0.079755,...,-0.062500,-0.011152,0.018248,-0.151261,-0.004219,-0.087156,-0.141361,-0.171779,-0.072368,-0.062937
18,Bangladesh,BGD,0.060241,0.087912,-0.058140,0.005780,0.130653,0.038647,0.000000,0.155102,...,0.381156,-0.749064,0.118812,-0.954839,-0.240000,0.155405,-0.184000,NaN,NaN,NaN
19,Bulgaria,BGR,-0.240072,0.062081,-0.117360,-0.078883,0.112388,0.125863,0.071949,0.151927,...,0.108824,-0.007144,0.050934,0.044406,0.032564,0.051754,0.056490,-0.029863,0.139724,0.071035
20,Bahrain,BHR,-0.162475,0.235385,0.102830,0.116463,0.152236,0.118277,0.091699,0.002684,...,0.092457,0.025956,0.258618,-0.775401,0.164971,0.120157,0.123326,-0.080869,0.048041,0.106596
21,"Bahamas, The",BHS,0.021433,-0.009271,-0.058901,0.031072,-0.021373,-0.003901,-0.016523,-0.001987,...,-0.044429,-0.102487,0.031387,-0.017831,0.053446,-0.040996,0.042747,0.038410,0.010007,-0.041696
22,Bosnia and Herzegovina,BIH,NaN,NaN,0.222973,-0.006803,0.140351,-0.230216,0.131250,0.030303,...,0.049689,-0.035370,0.147945,0.068878,0.107062,0.170132,0.013060,0.209440,0.128535,0.157096
23,Belarus,BLR,0.313675,0.076923,0.285915,-3.739653,-0.248333,0.016393,0.031746,0.015625,...,-0.160221,0.047368,0.203688,-0.028448,0.981076,0.017928,-0.161287,-0.225579,0.598954,0.011284
24,Belize,BLZ,0.015038,0.089041,0.170455,0.027624,0.076531,0.000000,0.020000,0.095023,...,-0.024490,-0.056034,0.041322,0.032000,0.097473,0.057823,0.084112,0.058651,0.116580,0.096019
25,Bermuda,BMU,0.007692,-0.026316,-0.027027,-0.042254,-0.069277,-0.194245,0.021127,-0.105058,...,-0.159091,-0.118644,-0.017241,0.016949,-0.017241,0.016949,-0.053571,-0.018182,0.098361,0.096296
26,Bolivia,BOL,0.092652,0.118310,0.082687,-0.131579,-0.072100,-0.009494,0.053892,0.217799,...,0.035354,0.008347,0.117820,0.045007,0.109023,0.000000,0.083812,0.012472,0.080292,0.154321
27,Brazil,BRA,0.253188,0.064561,0.408468,0.056589,0.038773,-0.113136,-0.261030,0.084200,...,0.004752,-0.051645,0.069560,0.050064,0.042980,0.023396,0.095956,-0.019664,0.036811,0.006374
28,Barbados,BRB,0.011186,0.052966,0.078125,0.005825,0.055046,-0.074951,-0.018072,0.062147,...,-0.012324,-0.094412,0.024436,0.063380,-0.059701,-0.053045,0.023033,0.119932,0.063291,0.048193
29,Brunei Darussalam,BRN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.207965,-0.439490,0.266355,0.115702,-0.157895,0.071111,-0.119403,0.077982,0.004566,0.154440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Latin America & the Caribbean (IDA & IBRD coun...,TLA,0.046505,-0.010288,0.064202,0.004179,0.059558,-0.036172,-0.042399,0.022993,...,0.042034,-0.030921,0.042940,0.055196,0.035305,0.022807,0.107512,0.070238,0.075021,0.085721
235,Timor-Leste,TLS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.388889,0.181818,-0.100000,0.215686,0.120690,0.265823,-0.316667,0.032258,0.060606,0.108108
236,Middle East & North Africa (IDA & IBRD countries),TMN,0.053562,0.083849,0.088278,0.131215,0.098155,0.004660,0.081838,0.055588,...,0.099920,0.058263,0.140380,-0.236698,0.078513,-0.009045,0.010387,-0.092254,-0.099881,0.152275
237,Tonga,TON,-0.074074,-0.038462,0.037037,0.129032,0.114286,-0.093750,0.135135,0.075000,...,0.080000,-0.094092,0.029724,-0.023913,0.029536,0.016598,0.043651,0.063197,0.089679,0.054400
238,South Asia (IDA & IBRD),TSA,0.030907,0.055545,0.027762,0.055029,0.061430,-0.075793,-0.038092,0.129822,...,0.035636,-0.037215,0.126598,0.111416,0.031022,0.081975,0.382365,0.014580,0.098569,0.067890
239,Sub-Saharan Africa (IDA & IBRD countries),TSS,0.120967,-0.003382,0.118009,0.038018,0.015074,0.029851,0.066565,0.045619,...,0.022650,-0.079945,0.099245,0.049692,0.034025,0.033734,0.035734,0.010925,0.086324,0.039330
240,Trinidad and Tobago,TTO,0.022556,0.179012,0.029940,0.067039,0.102757,-0.041775,0.002604,0.061125,...,-0.027460,-0.042959,-0.079897,0.099768,0.052747,-0.048387,-0.053398,0.063636,-0.075795,-0.035443
241,Tunisia,TUN,-0.060489,0.088670,0.096439,0.023593,0.044682,0.061073,-0.063784,0.009777,...,0.040851,0.095806,0.003960,-0.362339,0.179026,0.048014,-0.026386,-0.336630,0.063767,0.188315
242,Turkey,TUR,0.110846,0.118805,-0.008929,-0.299869,0.280931,0.111008,0.156919,0.041301,...,0.123187,0.013085,0.037527,0.094939,0.029245,0.055484,0.050639,-0.008435,-0.303377,0.194463
243,Tuvalu,TUV,0.100000,0.000000,0.000000,0.090909,0.000000,0.000000,0.153846,0.071429,...,0.352941,-0.062500,0.058824,-0.416667,-0.090909,0.153846,0.071429,0.416667,0.040000,0.000000
244,Tanzania,TZA,0.095238,0.092219,0.228889,0.202128,-0.228758,0.083832,0.089091,0.003623,...,0.077333,-0.079137,0.078249,0.105575,0.191755,0.018815,0.044924,-0.008152,0.104623,0.032941
245,Uganda,UGA,0.080460,0.005714,0.102564,-0.031746,0.020725,0.058537,0.192913,0.167213,...,0.239336,-0.045849,0.146934,0.178106,0.038429,0.007463,0.047393,0.028396,0.015117,0.056348
246,Ukraine,UKR,0.035807,0.490077,-0.217461,-0.466919,0.341937,0.298997,0.127698,0.159581,...,0.091438,-0.223627,0.019101,0.009900,0.069439,0.067204,-0.940765,-0.022852,0.067877,0.063036
247,Upper middle income,UMC,0.098477,0.020477,0.035744,0.054744,0.115145,0.041896,0.066527,-0.031202,...,0.036097,-0.031211,0.069177,0.066367,0.071302,0.041220,0.039942,0.031376,0.014808,0.069699
248,Uruguay,URY,0.060409,0.070812,-0.070735,-0.043415,-0.053354,-0.040169,-0.503975,0.114085,...,0.095459,0.056934,0.126647,0.176409,-0.060111,-0.004473,-0.000373,0.032816,0.086928,0.173381
249,United States,USA,0.068210,0.026755,-0.029972,0.043951,0.053261,-0.091866,-0.076777,-0.057329,...,0.032272,-0.052701,0.081770,0.044746,0.057548,0.047689,0.067007,0.035385,-0.017891,0.006940
250,Uzbekistan,UZB,0.468208,0.819792,-0.183724,-0.665298,-0.612583,0.124638,-0.039157,-0.437229,...,0.155285,0.120165,-0.246154,NaN,NaN,NaN,-0.057465,0.029197,0.053774,0.246468
251,St. Vincent and the Grenadines,VCT,-0.034483,0.107692,0.029851,0.014706,0.068493,-0.028169,0.089744,0.012658,...,-0.071429,-0.120000,-0.041667,0.027027,0.000000,-0.027778,-0.014085,0.053333,0.050633,-0.039474
252,"Venezuela, RB",VEN,0.077734,0.067568,-0.188321,-0.166951,-0.251599,0.196918,-0.351852,-0.281899,...,-0.081545,-0.243772,-0.068441,0.115966,0.397773,-0.002028,-0.150525,-0.086185,-0.312812,-0.407494
253,British Virgin Islands,VGB,0.102459,0.000000,0.125448,0.017606,-0.044118,0.081081,-0.049645,-0.014388,...,-0.034682,-0.119741,0.063636,0.023669,0.037037,0.040984,0.051813,0.017812,0.036765,-0.217910
254,Virgin Islands (U.S.),VIR,-0.217158,0.050891,0.068720,0.128099,0.113553,-0.036053,-0.013462,0.033457,...,-0.022648,-0.019538,0.015734,-0.008818,0.084006,-0.049153,0.040650,0.042056,0.037481,NaN
255,Vietnam,VNM,0.159303,0.063520,-0.128947,0.147026,0.167290,0.081545,0.113394,-0.081927,...,0.001653,-0.130504,0.258020,0.160293,0.121787,0.095615,0.038354,0.008812,0.206631,0.225120
256,Vanuatu,VUT,0.043478,0.080000,0.038462,-0.019608,0.120690,-0.094340,-0.081633,0.020000,...,0.104972,0.101291,-0.036008,-0.034043,0.131238,0.016364,-0.009174,-0.211111,0.053628,0.127523
257,World,WLD,0.055255,0.050921,0.029793,0.039796,0.074077,0.001267,0.028901,-0.013583,...,0.017285,-0.043260,0.061522,0.041284,0.054093,0.047103,0.045468,0.038771,0.035388,0.067829
258,Samoa,WSM,0.068493,-0.073529,0.128205,0.082353,0.034091,0.000000,0.011236,0.032609,...,0.008475,0.032787,0.000000,-0.008264,0.039683,-0.086207,0.036545,0.059375,0.044776,0.082192
259,Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,"Yemen, Rep.",YEM,0.175676,0.075000,0.090909,-0.517241,0.205479,0.039474,0.224490,0.367742,...,0.073314,0.004864,-0.002927,-0.236429,0.051487,0.117172,0.027027,-1.774748,NaN,NaN
261,South Africa,ZAF,0.086877,0.012259,0.131891,0.026825,-0.003065,-0.014688,0.100000,0.011530,...,0.052231,-0.367941,0.131533,0.031778,0.092403,0.036594,0.001257,-0.072439,0.113501,0.023432
262,Zambia,ZMB,0.382576,0.225806,0.058011,0.103960,0.115974,0.071138,0.129204,-0.368039,...,-0.104680,-0.143662,0.128834,0.114130,-0.071013,0.061202,0.033791,-0.016094,0.025105,0.117267
263,Zimbabwe,ZWE,0.113338,-0.195359,0.360766,0.071111,-0.143874,0.112765,-0.086232,0.095301,...,-0.281186,0.030243,0.099151,0.075939,-0.350613,0.021277,0.025000,0.086048,0.051199,0.105241

In [133]:
df1.loc[df['Region'].notnull()]
df1.dropna(thresh=2)

,Country Name,Country Code,1996,1997,1998,1999,2000,2001,2002,2003,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Aruba,ABW,2.200000e+04,9.000000e+03,-3.000000e+03,3.600000e+04,3.800000e+04,-3.000000e+04,-4.800000e+04,-1.000000e+03,...,5.500000e+04,-1.400000e+04,1.100000e+04,4.500000e+04,3.500000e+04,7.500000e+04,9.300000e+04,1.530000e+05,-1.230000e+05,-3.150000e+04
1,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Angola,AGO,1.200000e+04,2.400000e+04,7.000000e+03,-7.000000e+03,6.000000e+03,1.600000e+04,2.400000e+04,1.600000e+04,...,9.900000e+04,7.200000e+04,5.900000e+04,5.600000e+04,4.700000e+04,1.220000e+05,-5.500000e+04,-3.000000e+03,-1.950000e+05,-1.360000e+05
3,Albania,ALB,-1.700000e+04,-1.680000e+05,6.500000e+04,1.870000e+05,-5.400000e+04,3.700000e+04,1.160000e+05,8.700000e+04,...,1.850000e+05,4.640000e+05,4.800000e+05,2.780000e+05,6.870000e+05,-2.990000e+05,4.840000e+05,4.430000e+05,2.860000e+05,5.730000e+05
4,Andorra,AND,NaN,NaN,NaN,NaN,6.020000e+05,5.670000e+05,-1.290000e+05,-2.490000e+05,...,-1.300000e+05,-2.290000e+05,-2.200000e+04,4.340000e+05,-4.000000e+03,9.000000e+04,3.500000e+04,3.000000e+05,1.680000e+05,NaN
5,Arab World,ARB,7.738276e+05,1.914274e+06,2.388762e+06,3.876347e+06,3.804145e+06,8.735998e+05,4.255279e+06,1.770076e+06,...,1.005642e+07,-8.411342e+05,1.086766e+07,-1.369359e+07,8.090393e+06,-2.947931e+05,5.459917e+06,-5.303268e+06,-2.490405e+06,5.851191e+06
6,United Arab Emirates,ARE,2.570000e+05,-9.600000e+04,5.150000e+05,4.020000e+05,5.140000e+05,2.270000e+05,1.311000e+06,4.260000e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Argentina,ARG,3.250000e+05,1.500000e+05,2.480000e+05,-1.140000e+05,1.100000e+04,-2.890000e+05,2.000000e+05,1.750000e+05,...,1.380000e+05,-3.920000e+05,1.017000e+06,3.800000e+05,-1.180000e+05,-3.410000e+05,6.850000e+05,-1.950000e+05,9.190000e+05,6.500000e+04
8,Armenia,ARM,1.000000e+03,1.000000e+04,9.000000e+03,9.000000e+03,4.000000e+03,7.800000e+04,3.900000e+04,4.400000e+04,...,4.700000e+04,1.700000e+04,1.090000e+05,7.400000e+04,2.050000e+05,1.210000e+05,1.200000e+05,-1.200000e+04,6.800000e+04,2.350000e+05
9,American Samoa,ASM,1.000000e+03,-9.000000e+03,1.000000e+04,5.000000e+03,3.000000e+03,-8.000000e+03,NaN,NaN,...,2.000000e+02,-8.000000e+02,-4.000000e+02,-5.000000e+02,0.000000e+00,-1.800000e+03,8.000000e+02,-1.300000e+03,-2.000000e+02,-1.000000e+02
10,Antigua and Barbuda,ATG,8.000000e+03,1.200000e+04,-6.000000e+03,-2.000000e+03,-2.500000e+04,8.000000e+03,3.000000e+03,2.100000e+04,...,4.000000e+03,-3.200000e+04,-4.000000e+03,1.100000e+04,6.000000e+03,-4.000000e+03,6.000000e+03,1.000000e+03,1.500000e+04,-1.800000e+04
11,Australia,AUS,4.390000e+05,1.530000e+05,-1.510000e+05,2.920000e+05,4.720000e+05,-7.500000e+04,-1.500000e+04,-9.500000e+04,...,-5.800000e+04,-9.600000e+04,3.000000e+05,-1.900000e+04,2.610000e+05,4.500000e+05,4.400000e+05,5.280000e+05,8.190000e+05,5.460000e+05
12,Austria,AUT,-8.300000e+04,-4.430000e+05,7.050000e+05,1.150000e+05,5.150000e+05,1.980000e+05,4.310000e+05,4.670000e+05,...,1.162000e+06,-5.800000e+05,6.490000e+05,1.008000e+06,1.139000e+06,6.620000e+05,4.780000e+05,1.437000e+06,1.393000e+06,1.339000e+06
13,Azerbaijan,AZE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.920000e+05,...,3.110000e+05,-3.800000e+04,2.750000e+05,2.820000e+05,4.240000e+05,1.440000e+05,3.000000e+04,-2.380000e+05,1.220000e+05,4.100000e+05
14,Burundi,BDI,-7.000000e+03,-1.600000e+04,4.000000e+03,1.100000e+04,3.000000e+03,7.000000e+03,3.800000e+04,0.000000e+00,...,1.000000e+04,1.000000e+04,-7.000000e+04,2.000000e+03,3.000000e+03,8.700000e+04,1.000000e+03,-1.040000e+05,5.600000e+04,1.120000e+05
15,Belgium,BEL,2.690000e+05,2.080000e+05,1.420000e+05,1.900000e+05,8.800000e+04,-5.000000e+03,2.680000e+05,-3.000000e+04,...,1.200000e+05,-3.500000e+05,3.710000e+05,3.080000e+05,6.600000e+04,1.240000e+05,2.030000e+05,4.680000e+05,-8.740000e+05,9.040000e+05
16,Benin,BEN,5.000000e+03,5.000000e+03,4.000000e+03,-7.200000e+04,1.600000e+04,-8.000000e+03,-1.600000e+04,1.030000e+05,...,2.000000e+03,2.000000e+03,9.000000e+03,1.000000e+04,1.100000e+04,1.100000e+04,1.100000e+04,1.300000e+04,1.200000e+04,1.400000e+04
17,Burkina Faso,BFA,7.000000e+03,7.000000e+03,2.200000e+04,-4.300000e+04,9.000000e+03,2.000000e+03,2.200000e+04,1.300000e+04,...,-1.700000e+04,-3.000000e+03,5.000000e+03,-3.600000e+04,-1.000000e+03,-1.900000e+04,-2.700000e+04,-2.800000e+04,-1.100000e+04,-9.000000e+03
18,Bangladesh,BGD,1.000000e+04,1.600000e+04,-1.000000e+04,1.000000e+03,2.600000e+04,8.000000e+03,0.000000e+00,3.800000e+04,...,1.780000e+05,-2.000000e+05,3.600000e+04,-1.480000e+05,-3.000000e+04,2.300000e+04,-2.300000e+04,NaN,NaN,NaN
19,Bulgaria,BGR,-6.710000e+05,1.850000e+05,-3.130000e+05,-1.950000e+05,3.130000e+05,4.010000e+05,2.470000e+05,6.150000e+05,...,6.290000e+05,-4.100000e+04,3.080000e+05,2.810000e+05,2.130000e+05,3.570000e+05,4.130000e+05,-2.120000e+05,1.153000e+06,6.310000e+05
20,Bahrain,BHR,-3.230000e+05,6.120000e+05,2.980000e+05,3.820000e+05,5.890000e+05,5.190000e+05,4.430000e+05,1.300000e+04,...,7.980000e+05,2.300000e+05,3.091000e+06,-5.220000e+06,1.330000e+06,1.101000e+06,1.289000e+06,-7.820000e+05,4.880000e+05,1.212000e+06
21,"Bahamas, The",BHS,3.500000e+04,-1.500000e+04,-9.000000e+04,4.900000e+04,-3.300000e+04,-6.000000e+03,-2.500000e+04,-3.000000e+03,...,-6.500000e+04,-1.360000e+05,4.300000e+04,-2.400000e+04,7.600000e+04,-5.600000e+04,6.100000e+04,5.700000e+04,1.500000e+04,-6.000000e+04
22,Bosnia and Herzegovina,BIH,NaN,NaN,3.300000e+04,-1.000000e+03,2.400000e+04,-3.200000e+04,2.100000e+04,5.000000e+03,...,1.600000e+04,-1.100000e+04,5.400000e+04,2.700000e+04,4.700000e+04,9.000000e+04,7.000000e+03,1.420000e+05,1.000000e+05,1.450000e+05
23,Belarus,BLR,7.340000e+04,1.950000e+04,1.015000e+05,-2.801000e+05,-1.490000e+04,1.000000e+03,2.000000e+03,1.000000e+03,...,-1.450000e+04,4.500000e+03,2.430000e+04,-3.300000e+03,6.013900e+06,1.119000e+05,-8.669000e+05,-9.893000e+05,6.549800e+06,1.248000e+05
24,Belize,BLZ,2.000000e+03,1.300000e+04,3.000000e+04,5.000000e+03,1.500000e+04,0.000000e+00,4.000000e+03,2.100000e+04,...,-6.000000e+03,-1.300000e+04,1.000000e+04,8.000000e+03,2.700000e+04,1.700000e+04,2.700000e+04,2.000000e+04,4.500000e+04,4.100000e+04
25,Bermuda,BMU,3.000000e+03,-1.000000e+04,-1.000000e+04,-1.500000e+04,-2.300000e+04,-5.400000e+04,6.000000e+03,-2.700000e+04,...,-4.200000e+04,-2.800000e+04,-4.000000e+03,4.000000e+03,-4.000000e+03,4.000000e+03,-1.200000e+04,-4.000000e+03,2.400000e+04,2.600000e+04
26,Bolivia,BOL,2.900000e+04,4.200000e+04,3.200000e+04,-4.500000e+04,-2.300000e+04,-3.000000e+03,1.800000e+04,9.300000e+04,...,2.100000e+04,5.000000e+03,8.000000e+04,3.200000e+04,8.700000e+04,0.000000e+00,7.300000e+04,1.100000e+04,7.700000e+04,1.750000e+05
27,Brazil,BRA,6.750000e+05,1.840000e+05,1.968000e+06,2.890000e+05,2.060000e+05,-5.400000e+05,-9.880000e+05,3.480000e+05,...,2.400000e+04,-2.480000e+05,3.590000e+05,2.720000e+05,2.440000e+05,1.360000e+05,6.170000e+05,-1.240000e+05,2.410000e+05,4.200000e+04
28,Barbados,BRB,5.000000e+03,2.500000e+04,4.000000e+04,3.000000e+03,3.000000e+04,-3.800000e+04,-9.000000e+03,3.300000e+04,...,-7.000000e+03,-4.900000e+04,1.300000e+04,3.600000e+04,-3.200000e+04,-2.700000e+04,1.200000e+04,7.100000e+04,4.000000e+04,3.200000e+04
29,Brunei Darussalam,BRN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.700000e+04,-6.900000e+04,5.700000e+04,2.800000e+04,-3.300000e+04,1.600000e+04,-2.400000e+04,1.700000e+04,1.000000e+03,4.000000e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Latin America & the Caribbean (IDA & IBRD coun...,TLA,1.886000e+06,-4.130000e+05,2.754000e+06,1.800000e+05,2.728000e+06,-1.599000e+06,-1.798000e+06,9.980000e+05,...,2.545000e+06,-1.816000e+06,2.635000e+06,3.585000e+06,2.377000e+06,1.571400e+06,8.299700e+06,5.831900e+06,6.734195e+06,8.416066e+06
235,Timor-Leste,TLS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.400000e+04,8.000000e+03,-4.000000e+03,1.100000e+04,7.000000e+03,2.100000e+04,-1.900000e+04,2.000000e+03,4.000000e+03,8.000000e+03
236,Middle East & North Africa (IDA & IBRD countries),TMN,7.708092e+05,1.317101e+06,1.520926e+06,2.602128e+06,2.158369e+06,1.029470e+05,1.969154e+06,1.416263e+06,...,4.427605e+06,2.741425e+06,7.683943e+06,-1.047634e+07,3.771092e+06,-4.305532e+05,4.996073e+05,-4.062677e+06,-3.999104e+06,7.192062e+06
237,Tonga,TON,-2.000000e+03,-1.000000e+03,1.000000e+03,4.000000e+03,4.000000e+03,-3.000000e+03,5.000000e+03,3.000000e+03,...,4.000000e+03,-4.300000e+03,1.400000e+03,-1.100000e+03,1.400000e+03,8.000000e+02,2.200000e+03,3.400000e+03,5.300000e+03,3.400000e+03
238,South Asia (IDA & IBRD),TSA,1.214850e+05,2.311675e+05,1.188396e+05,2.492783e+05,2.964886e+05,-3.400360e+05,-1.646255e+05,6.447661e+05,...,2.981165e+05,-3.001515e+05,1.169065e+06,1.157872e+06,3.327103e+05,9.576958e+05,7.232564e+06,2.798594e+05,2.098945e+06,1.550963e+06
239,Sub-Saharan Africa (IDA & IBRD countries),TSS,1.783089e+06,-4.968772e+04,1.965581e+06,6.582543e+05,2.650005e+05,5.409191e+05,1.292198e+06,9.279223e+05,...,6.930958e+05,-2.265261e+06,3.121981e+06,1.644924e+06,1.165967e+06,1.196362e+06,1.314256e+06,4.062656e+05,3.513234e+06,1.666178e+06
240,Trinidad and Tobago,TTO,6.000000e+03,5.800000e+04,1.000000e+04,2.400000e+04,4.100000e+04,-1.600000e+04,1.000000e+03,2.500000e+04,...,-1.200000e+04,-1.800000e+04,-3.100000e+04,4.300000e+04,2.400000e+04,-2.100000e+04,-2.200000e+04,2.800000e+04,-3.100000e+04,-1.400000e+04
241,Tunisia,TUN,-2.350000e+05,3.780000e+05,4.550000e+05,1.140000e+05,2.260000e+05,3.290000e+05,-3.230000e+05,5.000000e+04,...,2.880000e+05,7.470000e+05,3.100000e+04,-2.082000e+06,1.253000e+06,3.530000e+05,-1.890000e+05,-1.804000e+06,3.650000e+05,1.328000e+06
242,Turkey,TUR,8.830000e+05,1.074000e+06,-8.000000e+04,-2.067000e+06,2.693000e+06,1.197000e+06,2.007000e+06,5.510000e+05,...,3.670000e+06,3.950000e+05,1.177000e+06,3.290000e+06,1.044000e+06,2.097000e+06,2.016000e+06,-3.330000e+05,-9.189000e+06,7.312000e+06
243,Tuvalu,TUV,1.000000e+02,0.000000e+00,0.000000e+00,1.000000e+02,0.000000e+00,0.000000e+00,2.000000e+02,1.000000e+02,...,6.000000e+02,-1.000000e+02,1.000000e+02,-5.000000e+02,-1.000000e+02,2.000000e+02,1.000000e+02,1.000000e+03,1.000000e+02,0.000000e+00
244,Tanzania,TZA,3.000000e+04,3.200000e+04,1.030000e+05,1.140000e+05,-1.050000e+05,4.200000e+04,4.900000e+04,2.000000e+03,...,5.800000e+04,-5.500000e+04,5.900000e+04,8.900000e+04,2.000000e+05,2.000000e+04,5.000000e+04,-9.000000e+03,1.290000e+05,4.200000e+04
245,Uganda,UGA,1.400000e+04,1.000000e+03,2.000000e+04,-6.000000e+03,4.000000e+03,1.200000e+04,4.900000e+04,5.100000e+04,...,2.020000e+05,-3.700000e+04,1.390000e+05,2.050000e+05,4.600000e+04,9.000000e+03,6.000000e+04,3.700000e+04,2.000000e+04,7.900000e+04
246,Ukraine,UKR,1.380000e+05,3.704000e+06,-1.350000e+06,-1.976000e+06,2.199000e+06,2.743000e+06,1.343000e+06,1.997000e+06,...,2.327000e+06,-4.651000e+06,4.050000e+05,2.120000e+05,1.598000e+06,1.658000e+06,-1.195900e+07,-2.840000e+05,9.050000e+05,8.970000e+05
247,Upper middle income,UMC,1.163830e+07,2.470678e+06,4.472504e+06,7.246593e+06,1.722559e+07,6.541673e+06,1.112786e+07,-5.061204e+06,...,8.925731e+06,-7.484141e+06,1.782075e+07,1.831201e+07,2.118420e+07,1.277337e+07,1.289208e+07,1.045532e+07,5.008649e+06,2.534081e+07
248,Uruguay,URY,1.300000e+05,1.640000e+05,-1.530000e+05,-9.000000e+04,-1.050000e+05,-7.600000e+04,-6.340000e+05,1.620000e+05,...,1.850000e+05,1.170000e+05,2.980000e+05,5.040000e+05,-1.620000e+05,-1.200000e+04,-1.000000e+03,9.100000e+04,2.640000e+05,6.370000e+05
249,United States,USA,3.171000e+06,1.278000e+06,-1.390000e+06,2.132000e+06,2.729000e+06,-4.311000e+06,-3.346000e+06,-2.363000e+06,...,1.872000e+06,-2.904000e+06,4.907000e+06,2.811000e+06,3.836000e+06,3.338000e+06,5.027000e+06,2.752000e+06,-1.367000e+06,5.340000e+05
250,Uzbekistan,UZB,8.100000e+04,7.870000e+05,-1.490000e+05,-3.240000e+05,-1.850000e+05,4.300000e+04,-1.300000e+04,-1.010000e+05,...,1.660000e+05,1.460000e+05,-2.400000e+05,NaN,NaN,NaN,-1.070000e+05,5.600000e+04,1.090000e+05,6.630000e+05
251,St. Vincent and the Grenadines,VCT,-2.000000e+03,7.000000e+03,2.000000e+03,1.000000e+03,5.000000e+03,-2.000000e+03,7.000000e+03,1.000000e+03,...,-6.000000e+03,-9.000000e+03,-3.000000e+03,2.000000e+03,0.000000e+00,-2.000000e+03,-1.000000e+03,4.000000e+03,4.000000e+03,-3.000000e+03
252,"Venezuela, RB",VEN,5.900000e+04,5.500000e+04,-1.290000e+05,-9.800000e+04,-1.180000e+05,1.150000e+05,-1.520000e+05,-9.500000e+04,...,-5.700000e+04,-1.370000e+05,-3.600000e+04,6.900000e+04,3.930000e+05,-2.000000e+03,-1.290000e+05,-6.800000e+04,-1.880000e+05,-1.740000e+05
253,British Virgin Islands,VGB,2.500000e+04,0.000000e+00,3.500000e+04,5.000000e+03,-1.200000e+04,2.400000e+04,-1.400000e+04,-4.000000e+03,...,-1.200000e+04,-3.700000e+04,2.100000e+04,8.000000e+03,1.300000e+04,1.500000e+04,2.000000e+04,7.000000e+03,1.500000e+04,-7.300000e+04
254,Virgin Islands (U.S.),VIR,-8.100000e+04,2.000000e+04,2.900000e+04,6.200000e+04,6.200000e+04,-1.900000e+04,-7.000000e+03,1.800000e+04,...,-1.300000e+04,-1.100000e+04,9.000000e+03,-5.000000e+03,5.200000e+04,-2.900000e+04,2.500000e+04,2.700000e+04,2.500000e+04,NaN
255,Vietnam,VNM,2.560000e+05,1.090000e+05,-1.960000e+05,2.620000e+05,3.580000e+05,1.900000e+05,2.980000e+05,-1.990000e+05,...,7.000000e+03,-4.890000e+05,1.303000e+06,9.640000e+05,8.340000e+05,7.240000e+05,3.020000e+05,7.000000e+04,2.069000e+06,2.909000e+06
256,Vanuatu,VUT,2.000000e+03,4.000000e+03,2.000000e+03,-1.000000e+03,7.000000e+03,-5.000000e+03,-4.000000e+03,1.000000e+03,...,9.500000e+03,1.020000e+04,-3.500000e+03,-3.200000e+03,1.420000e+04,1.800000e+03,-1.000000e+03,-1.900000e+04,5.100000e+03,1.390000e+04
257,World,WLD,3.064200e+07,2.975325e+07,1.794249e+07,2.496053e+07,5.017913e+07,8.592473e+05,2.018535e+07,-9.359849e+06,...,1.618543e+07,-3.882707e+07,5.883841e+07,4.118300e+07,5.704689e+07,5.212992e+07,5.271808e+07,4.676559e+07,4.425177e+07,9.098946e+07
258,Samoa,WSM,5.000000e+03,-5.000000e+03,1.000000e+04,7.000000e+03,3.000000e+03,0.000000e+00,1.000000e+03,3.000000e+03,...,1.000000e+03,4.000000e+03,0.000000e+00,-1.000000e+03,5.000000e+03,-1.000000e+04,4.400000e+03,7.600000e+03,6.000000e+03,1.200000e+04
259,Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,"Yemen, Rep.",YEM,1.300000e+04,6.000000e+03,8.000000e+03,-3.000000e+04,1.500000e+04,3.000000e+03,2.200000e+04,5.700000e+04,...,7.500000e+04,5.000000e+03,-3.000000e+03,-1.960000e+05,4.500000e+04,1.160000e+05,2.750000e+04,-6.508000e+05,NaN,NaN
261,South Africa,ZAF,4.270000e+05,6.100000e+04,7.560000e+05,1.580000e+05,-1.800000e+04,-8.500000e+04,6.430000e+05,7.500000e+04,...,5.010000e+05,-2.580000e+06,1.062000e+06,2.650000e+05,8.490000e+05,3.490000e+05,1.200000e+04,-6.450000e+05,1.140000e+06,2.410000e+05
262,Zambia,ZMB,1.010000e+05,7.700000e+04,2.100000e+04,4.200000e+04,5.300000e+04,3.500000e+04,7.300000e+04,-1.520000e+05,...,-8.500000e+04,-1.020000e+05,1.050000e+05,1.050000e+05,-6.100000e+04,5.600000e+04,3.200000e+04,-1.500000e+04,2.400000e+04,1.270000e+05
263,Zimbabwe,ZWE,1.810000e+05,-2.610000e+05,7.540000e+05,1.600000e+05,-2.830000e+05,2.500000e+05,-1.760000e+05,2.150000e+05,...,-5.500000e+05,6.100000e+04,2.220000e+05,1.840000e+05,-6.290000e+05,3.900000e+04,4.700000e+04,1.770000e+05,1.110000e+05,2.550000e+05

In [132]:
del df1